##################################################################
# Lunge rates and prey consumption calculations and visualizations ----
##################################################################

# load data and packages and functions ----
library(data.table)
library(readxl)
library(forcats)
library(tidyverse)
library(ggstance)
library(mgcv)
library(lme4)
library(lmerTest)
library(MuMIn)
library(ggpubr)


SE = function(x){sd(x)/sqrt(sum(!is.na(x)))}

# Abbreviate a binomial e.g. Balaenoptera musculus -> B. musculus
abbr_binom <- function(binom) {
  paste(str_sub(binom, 1, 1), 
        str_extract(binom, " .*"), 
        sep = ".")
}

# Raincloud plot code----
### This script creates an R function to generate raincloud plots, then simulates
### data for plots. If using for your own data, you only need lines 1-80.
### It relies largely dddon code previously written by David Robinson
### (https://gist.github.com/dgrtwo/eb7750e74997891d7c20)
### and the package ggplot2 by Hadley Wickham

# Check if required packages are installed  
packages <- c("cowplot", "readr", "ggplot2", "dplyr", "lavaan", "smooth", "Hmisc")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
}

# Load packages
library(ggplot2)
# Defining the geom_flat_violin (Raincloud) function ----
# Note: the below code modifies the
# existing github page by removing a parenthesis in line 50

"%||%" <- function(a, b) {
  if (!is.null(a)) a else b
}

geom_flat_violin <- function(mapping = NULL, data = NULL, stat = "ydensity",
                             position = "dodge", trim = TRUE, scale = "area",
                             show.legend = NA, inherit.aes = TRUE, ...) {
  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomFlatViolin,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      trim = trim,
      scale = scale,
      ...
    )
  )
}

#' @rdname ggplot2-ggproto
#' @format NULL
#' @usage NULL
#' @export
GeomFlatViolin <-
  ggproto("GeomFlatViolin", Geom,
          setup_data = function(data, params) {
            data$width <- data$width %||%
              params$width %||% (resolution(data$x, FALSE) * 0.9)
            
            # ymin, ymax, xmin, and xmax define the bounding rectangle for each group
            data %>%
              group_by(group) %>%
              mutate(
                ymin = min(y),
                ymax = max(y),
                xmin = x,
                xmax = x + width / 2
              )
          },
          
          draw_group = function(data, panel_scales, coord) {
            # Find the points for the line to go all the way around
            data <- transform(data,
                              xminv = x,
                              xmaxv = x + violinwidth * (xmax - x)
            )
            
            # Make sure it's sorted properly to draw the outline
            newdata <- rbind(
              plyr::arrange(transform(data, x = xminv), y),
              plyr::arrange(transform(data, x = xmaxv), -y)
            )
            
            # Close the polygon: set first and last point the same
            # Needed for coord_polar and such
            newdata <- rbind(newdata, newdata[1, ])
            
            ggplot2:::ggname("geom_flat_violin", GeomPolygon$draw_panel(newdata, panel_scales, coord))
          },
          
          draw_key = draw_key_polygon,
          
          default_aes = aes(
            weight = 1, colour = "grey20", fill = "white", size = 0.5,
            alpha = NA, linetype = "solid"
          ),
          
          required_aes = c("x", "y")
  )








# # feeding rates generated by Max----

# for CATS data
load("~/Documents/Research Data/Whale research/ShirelCh2/rates_CATS.RData")

lunge_rates_CATS <- lunge_rates %>% 
  mutate_at(vars(Rate), ~replace(., is.nan(.), 0)) %>% 
  mutate(tag_type = "CATS")


# for DTAG data

load("~/Documents/Research Data/Whale research/ShirelCh2/rates_DTAG only_9.17.19_long.RData")
  
lunge_rates_DTAG <- dtag_lunges_long %>% 
 mutate_at(vars(Rate), ~replace(., is.nan(.), 0)) %>% 
  rename(`Time (hours)` = Hours) %>% 
  mutate(prey_general = "Krill",
         Study_Area = "SoCal",
         Region = "Eastern North Pacific",
         tag_type = "DTAG")


load("~/Documents/Research Data/Whale research/ShirelCh2/rates_DTAG_problems addressed.RData")

lunge_rates_DTAG_problems_addressed <- dtag_lunges_long %>% 
  mutate_at(vars(Rate), ~replace(., is.nan(.), 0)) %>% 
  rename(`Time (hours)` = Hours) %>% 
  mutate(prey_general = "Krill",
         Study_Area = "SoCal",
         Region = "Eastern North Pacific",
         tag_type = "DTAG")

lunge_rates_all <- lunge_rates_DTAG_problems_addressed %>% 
  bind_rows(lunge_rates_CATS) %>% 
  mutate(SpeciesCode = substr(ID, 1, 2))

## REMOVE BAD DEPLOYMENTS ###
bad_ID <- read_csv("Bad ID.csv")

# adding in Bryde's deployments from 2018
Brydes_lunges <- read_csv("Brydes_2018_lunge_rates.csv") %>% 
  select(ID, study_area, region, prey_general, duration_h, daylight_h, twilight_h, night_h, total_lunges) 


Brydes_lunges_long <- Brydes_lunges %>% 
  pivot_longer(duration_h:night_h, names_to = "Phase", values_to = "Time (hours)") %>% 
  rename(Study_Area = study_area,
         Region = region, 
         Lunges = total_lunges) %>% 
  mutate(prey_general = "Fish",
         tag_type = "CATS",
         Phase = case_when(Phase == "duration_h" ~ "Total",
                           Phase == "daylight_h" ~ "Day",
                           Phase == "twilight_h" ~ "Twilight",
                           Phase == "night_h" ~ "Night"),
         Rate = Lunges/`Time (hours)`) %>% 
  mutate_at(vars(Rate), ~replace(., is.infinite(.), 0))


#put all deployments together (DTAG and CATS)
lunge_rates_all <- lunge_rates_DTAG_problems_addressed %>% 
  bind_rows(lunge_rates_CATS, Brydes_lunges_long) %>% 
  mutate(SpeciesCode = substr(ID, 1, 2)) %>% 
  anti_join(bad_ID, by = "ID")



# READ IN and COMBINE DATA
# Species-specific average length data (from Shirel's paper) to recalculate average engulfment capacity----
v_data <- read_csv("MWmeasurements.csv") %>%
  group_by(Species) %>%
  dplyr::summarize(med_TLm = median(TLm)) %>%
  rename(CommonName = Species) %>%
  mutate(SpeciesCode = case_when(CommonName ==  "Blue Whale" ~ "bw",
                                 CommonName == "Fin Whale"~ "bp",
                                 CommonName ==  "Humpback Whale" ~ "mn",
                                 CommonName == "Minke Whale" ~ "bb",
                                 CommonName == "Bryde's Whale" ~ "be",
                                 CommonName == "Sei Whale" ~ "bs"))
# # # v_data$L <- v_data$MW*0.9766  #creates column that converts MW (kg) to liters

# Allometric equations from Shirel's paper----
# creating fucntions from Shirel's paper for MW (in kg) for engulfment capacity in liters for each species where we have a known length
engulf_allo <- tribble(
  ~SpeciesCode, ~slope,   ~intercept,
  "bb",     3.10910,  0.69969,
  "be",     3.1453,   0.5787,
  "bs",     3.05591,   0.77219,
  "bp",     3.54883,  0.15604,
  "bw",     3.667316, -0.014078,
  "mn",     3.24603,  0.85934
)




# Prey data from Dave Cade, recieved on 10/19 ----
#MRY SOCAL COMBINATION; THINK ABOUT WHAT COMBINATIONS TO USE
# mean values example
#(log(0.8) + log(0.4))/2
#answer = -0.5697171
# to get back to biomass units exp^answer above; exp is e in R, raise e to logged average to get back to kg units


pooled_log_mean <- function(m1, m2) {
  a = (log(m1) + log(m2))/2
  exp(a)  #turns values back into biomass units (kg/m3)
}


# pooled sd
pooled_sd_mean <- function(sd1, sd2, n1, n2) {
  
  a=log(sd1)
  b=log(sd2)
  
  pooled_sd = sqrt(((n1-1)*a^2 + (n2-1)*b^2)/(n1+n2-2))  # https://www.statisticshowto.datasciencecentral.com/pooled-standard-deviation/ 
  
  exp(pooled_sd)   #turns values back into biomass units (kg/m3)
}


# read in, clean, combine data
MRY_krill_data <- read_csv("MontereyKrillData (1).csv") %>% 
  filter(!Species %in% c("bigBW", "bb")) %>% 
  select(Species:BiomassTop50sd) %>%    # remember: biomass is in kg/m3
  mutate(
    Biomass_hyp_low = exp(log(Biomass) + log(0.17)),
    Study_Area = "Monterey",
    Region = "Eastern North Pacific") %>% 
  rename(SpeciesCode = "Species") 

SoCal_krill_data <- read_csv("SoCalKrillData (1).csv") %>% 
  filter(!Species %in% c("bigBW", "bb")) %>% 
  select(Species:BiomassTop50sd) %>%    # remember: biomass is in kg/m3
  mutate(
    Biomass_hyp_low = exp(log(Biomass) + log(0.17)),
    Study_Area = "SoCal",
    Region = "Eastern North Pacific") %>% 
  rename(SpeciesCode = "Species") 

# combining Monterey and SoCal prey data
ENP_krill_data <- rbind(MRY_krill_data, SoCal_krill_data) %>% 
  #mutate(Study_Area2 = Study_Area) %>% 
  pivot_wider(names_from = Study_Area, values_from = c(`Num Days`:Biomass_hyp_low)) %>% 
  #rename(Study_Area = Study_Area2) %>% 
  mutate(
    `Num Days` = `Num Days_Monterey` + `Num Days_SoCal`, 
    Biomass_hyp_low = pooled_log_mean(Biomass_hyp_low_Monterey, Biomass_hyp_low_SoCal),
    Biomass = pooled_log_mean(Biomass_Monterey, Biomass_SoCal),
    `Biomass sd` = pooled_sd_mean(`Biomass sd_Monterey`, `Biomass sd_SoCal`, `Num Days_Monterey`, `Num Days_SoCal`),
    BiomassTop50 = pooled_log_mean(BiomassTop50_Monterey, BiomassTop50_SoCal),
    BiomassTop50sd = pooled_sd_mean(`BiomassTop50sd_Monterey`, `BiomassTop50sd_SoCal`, `Num Days_Monterey`, `Num Days_SoCal`),
    Study_Area = NA
    # 
    # `Num Days` = coalesce(`Num Days_Monterey`, `Num Days_SoCal`),
    # Biomass_hyp_low = coalesce(Biomass_hyp_low_Monterey, Biomass_hyp_low_SoCal),
    # Biomass = coalesce(Biomass_Monterey, Biomass_SoCal),
    # `Biomass sd` = coalesce(`Biomass sd_Monterey`, `Biomass sd_SoCal`),
    # BiomassTop50 = coalesce(BiomassTop50_Monterey, BiomassTop50_SoCal),
    # BiomassTop50sd = coalesce(`BiomassTop50sd_Monterey`, `BiomassTop50sd_SoCal`)
  ) %>% 
  select(-c(`Num Days_Monterey`:Biomass_hyp_low_SoCal)) 


WAP_krill_data <- read_csv("AntarcticKrillData (1).csv") %>% 
  filter(!Species %in% c("bigBW")) %>% 
  select(Species:BiomassTop50sd) %>%    # remember: biomass is in kg/m3
  mutate(
    Biomass_hyp_low = NA,
    Study_Area = "Antarctic",
    Region = "Antarctic") %>% 
  rename(SpeciesCode = "Species")
 
SA_krill_data <- read_csv("SouthAfricaKrillData (1).csv") %>% 
  filter(!Species %in% c("bigBW", "bw", "bp", "bb")) %>% 
  select(Species:BiomassTop50sd) %>%    # remember: biomass is in kg/m3
  mutate(
    Biomass_hyp_low = exp(log(Biomass) + log(0.17)),
    Study_Area = "South Africa",
    Region = "South Africa") %>% 
  rename(SpeciesCode = "Species") 

All_krill_data <- rbind(MRY_krill_data, SoCal_krill_data, WAP_krill_data, SA_krill_data) 

All_krill_data_ENPcombined <- rbind(ENP_krill_data, WAP_krill_data, SA_krill_data) 




# Whale population data---- 
#Current data from IUCN 2019 Redlist, whaling data compiled in Rocha et al. 2014
pop_data <- read_excel("Filtration project_Whale population and feeding information.xlsx", sheet = 1)


#Read in tag guide----
tag_guide <- read_excel("TAG GUIDE_9.5.19.xlsx", skip = 2) %>%  # Skips first two rows
  rename(Study_Area = `Study_Area     _`,
         SpeciesCode = `Spec      _`,
         whaleLength = `Drone  _`) 

tag_guide_ENP <- tag_guide %>% 
  filter(Study_Area %in% c("Monterey", "Cordell Bank", "SoCal", "San Diego", "WA Coast", "Alaska"))
#View(tag_guide_ENP)  # this is for CATS tags only, need to add in DTags for full dataset


# Master filtration rate file----
filtration_master <- lunge_rates_all %>%
  left_join(select(tag_guide, ID, SpeciesCode, Study_Area, whaleLength), by = c("ID", "SpeciesCode")) %>%
  mutate(Study_Area = coalesce(Study_Area.x, Study_Area.y)) %>% 
  select(-c(Study_Area.x, Study_Area.y)) %>% 
  filter(SpeciesCode %in% c("bb", "be", "bp", "bw", "mn", "bs")) %>% 
  mutate(
    Year = substr(ID, 3, 4),
    whaleLength = parse_number(whaleLength),
    Study_Area = replace_na(Study_Area, "SoCal"),
    CommonName = case_when(
      SpeciesCode == "bw" ~ "Blue Whale",
      SpeciesCode == "bp" ~ "Fin Whale",
      SpeciesCode == "bs" ~ "Sei Whale",
      SpeciesCode == "mn" ~ "Humpback Whale",
      SpeciesCode %in% c("ba", "bb") ~ "Minke Whale", 
      TRUE ~ "Bryde's Whale"),
    Species = case_when(
      SpeciesCode == "bw" ~ "Balaenoptera musculus",
      SpeciesCode == "bp" ~ "Balaenoptera physalus",
      SpeciesCode == "mn" ~ "Megaptera novaeangliae",
      SpeciesCode %in% c("bb","ba") ~ "Balaenoptera bonaerensis", 
      SpeciesCode == "be" ~ "Balaenoptera edeni",
      SpeciesCode == "bs" ~ "Balaenoptera borealis"),
    Region = case_when(
      Study_Area %in% c("Monterey", "SoCal", "Cordell Bank", "San Diego", "WA Coast", "Alaska", "Everett")  ~ "Eastern North Pacific",
      Study_Area %in% c("Stellwagen", "Norway", "Azores", "Greenland") ~ "North Atlantic",
      Study_Area == "South Africa" ~ "South Africa",
      Study_Area == "Antarctic" ~ "Antarctic",
      Study_Area == "Chile" ~ "Chile",
      Study_Area == "Falklands" ~ "Falklands")) %>%  
  # Join population numbers
  left_join(pop_data, by = "Species") %>% 
  # Join species-median size data
  left_join(select(v_data, -CommonName), by = "SpeciesCode") %>% 
  # Join allometric equations
  left_join(engulf_allo, by = "SpeciesCode") %>% 
  # Calculate engulfment volumes
  mutate(
    BestLengthEst = coalesce(whaleLength, med_TLm),
    Engulfment_L = BestLengthEst ^ slope * 10 ^ intercept * 0.9766,
    EngulfVolPerHr = Engulfment_L*Rate) %>%     #volume engulfed in liters per hour
  # adding in krill prey data. Remember: biomass is in kg/m3 here, need to convert back to log to average by region
  left_join(All_krill_data_ENPcombined, by = c("SpeciesCode", "Region")) %>% 
  mutate(Study_Area = coalesce(Study_Area.x, Study_Area.y)) %>% 
  select(-c(Study_Area.x, Study_Area.y)) %>%
  ungroup %>% 
  #converting to log scale to later sample from log-normal distirbution
  mutate(
    prey_hyp_low_lnmean = log(Biomass_hyp_low),
    prey_hyp_low_lnsd = log(`Biomass sd`),
    prey_best_low_lnmean = log(Biomass),
    prey_best_low_lnsd = log(`Biomass sd`),
    prey_best_upper_lnmean = log(BiomassTop50),
    prey_best_upper_lnsd = log(BiomassTop50sd))


#see what deployments are missing and determine if they can be added
missing_deploy <- tag_guide %>% 
  anti_join(select(filtration_master, ID, Study_Area), by = "ID") %>% 
  mutate(`Total Tag On Time HH:MM:SS _` = as.numeric(`Total Tag On Time HH:MM:SS _`)) %>% 
  filter(SpeciesCode %in% c("bb", "be", "mn", "bp", "bw"),
         `PRH _` == "Y",
         "Total Tag On Time HH:MM:SS _" > 1)


filtration_master %>%
  group_by(Species) %>%
  summarise(med_length = mean(whaleLength, na.rm = TRUE))




# plots and descriptions of raw data----
length_MW <- filtration_master %>%
  filter(Phase =="Total") %>% 
  drop_na(whaleLength) %>% 
  group_by(Species) %>% 
  summarise(
    sample_size = n_distinct(ID),
    med_length = round(median(whaleLength), 2),
    IQR25_length = round(quantile(whaleLength, probs = 0.25, na.rm = TRUE), 2),
    IQR75_length = round(quantile(whaleLength, probs = 0.75, na.rm = TRUE), 2),
    med_engulf_cap = round(median(Engulfment_L/1000),2),
    IQR25_engulf_cap = round(quantile(Engulfment_L, probs = 0.25, na.rm = TRUE)/1000, 2),
    IQR75_engulf_cap = round(quantile(Engulfment_L, probs = 0.75, na.rm = TRUE)/1000, 2)) %>% 
  unite("Length IQR", c(IQR25_length, IQR75_length), sep = "-") %>% 
  unite("Engulf Cap IQR", c(IQR25_engulf_cap, IQR75_engulf_cap), sep = "-") %>% 
  arrange(med_length)


Feeding_rates_krill <- filtration_master %>%
  filter(prey_general =="Krill", Phase != "Total", Region != "Chile") %>% 
  group_by(Species, Phase, Region) %>% 
  summarise(
    sample_size = n_distinct(ID),
    med_rate = round(median(Rate), 2),
    IQR25_rate = round(quantile(Rate, probs = 0.25, na.rm = TRUE), 2),
    IQR75_rate = round(quantile(Rate, probs = 0.75, na.rm = TRUE), 2)) %>% 
  pivot_wider(names_from = Phase, values_from = med_rate:IQR75_rate) %>% 
  unite("Day rate IQR", c(IQR25_rate_Day, IQR75_rate_Day), sep = "-") %>% 
  unite("Twilight rate IQR", c(IQR25_rate_Twilight, IQR75_rate_Twilight), sep = "-") %>% 
  unite("Night rate IQR", c(IQR25_rate_Night, IQR75_rate_Night), sep = "-") 

  
pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")
  
filter(Region == "Eastern North Pacific", ID != "bw180904-44") %>% 
  group_by(ID, Species) %>% 
  summarise(whaleLength = first(whaleLength)) %>% 
  ungroup %>% 
  mutate(sp_lbl = factor(abbr_binom(Species)) %>% fct_rev) %>% 
  
  
All_droned_lengths <- filtration_master %>% 
  #filter(SpeciesCode %in% c("bw", "bp", "mn")) %>% 
  filter(ID != "bw180904-44") %>% 
  group_by(ID, Species) %>% 
  summarise(whaleLength = first(whaleLength)) %>% 
  ungroup %>% 
  mutate(sp_lbl = factor(abbr_binom(Species)) %>% fct_rev) %>% 
  ggplot(aes(x = sp_lbl, 
             y = whaleLength,
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, outlier.shape = NA, alpha = 0.5) +
  geom_point(position = position_jitter(width = .05), alpha = 0.6) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  labs(x = "Species",
       y = "Measured length (m)") +
  theme_classic(base_size = 18) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
All_droned_lengths
  
dev.copy2pdf(file="All_droned_lengths.pdf", width=12, height=8)


Engulfment_capacity <- filtration_master %>% 
  #filter(ID != "bw180904-44") %>% 
  drop_na(whaleLength) %>% 
  group_by(ID, Species, Engulfment_L) %>% 
  summarise(whaleLength = first(whaleLength)) %>%
  mutate(Engulfment_m3 = Engulfment_L/1000) %>%
  ungroup %>% 
  ggplot(aes(x = fct_reorder(abbr_binom(Species), Engulfment_m3), y = Engulfment_m3,
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.075, y = 0), alpha = .8) +
  geom_boxplot(width = .1, outlier.shape = NA, alpha = 0.5) +
  geom_point(position = position_jitter(width = .05), alpha = 0.6) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  labs(x = "Species",
       y = bquote('Engulfment capacity'~(m^3))) +
  scale_y_log10(labels = scales::comma) +
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Engulfment_capacity

dev.copy2pdf(file="Engulfment_capacity.pdf", width=14, height=6.5)



Feeding_rate_h <- filtration_master %>% 
  filter(prey_general %in% c("Fish", "Krill"), 
         Phase == "Total",
         `Time (hours)` > 1) %>%       # %in% c("Day", "Twilight", "Night")) %>%      
  group_by(ID, Species, Engulfment_L, Phase, Rate, prey_general, Year) %>% 
  summarise(whaleLength = first(whaleLength)) %>%
  ungroup %>%
  mutate(prey_general = factor(prey_general),
         prey_general = recode_factor(prey_general, 
                                      Fish = "Fish-feeding", 
                                      Krill = "Krill-feeding"),
         Species = fct_relevel(factor(abbr_binom(Species)), "B. bonaerensis", "M. novaeangliae","B. physalus", "B. musculus"),
         
         Engulfment_m3 = Engulfment_L/1000) %>% 
  ungroup %>%
  ggplot(aes(x = Species, y = Rate,
             fill = Species)) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_point(position = position_jitter(width = .05), alpha = 0.6) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  facet_grid(prey_general~., scales = "free", space = "free") +  
  labs(x = "Species",
       y = bquote('Feeding rate'~(lunges~h^-1))) + 
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Feeding_rate_h

dev.copy2pdf(file="Feeding_rate_h.pdf", width=14, height=6.5)

prey_consumed_h <- filtration_master %>% 
  filter(Phase == "Total") %>%       # %in% c("Day", "Twilight", "Night")) %>%      
  group_by(ID, Species, Engulfment_L, Phase, Rate, prey_general, Year) %>% 
  summarise(whaleLength = first(whaleLength)) %>%
  mutate(Engulfment_m3 = Engulfment_L/1000) %>%
  ungroup %>% 
  ggplot(aes(x = fct_reorder(abbr_binom(Species), Rate), y = Rate,
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_point(position = position_jitter(width = .05), alpha = 0.6) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  #facet_grid(.~prey_general, scales = "free", space = "free") +  # freeing scales doesn't work with flat_violin plots
  labs(x = "Species",
       y = bquote('Feeding rate'~(lunges~h^-1))) + 
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
prey_consumed_h


dev.copy2pdf(file="Feeding_rate_h.pdf", width=14, height=6.5)



################################
## CREATE SAMPLING FUNCTION----
################################

#determining daily feeding rates ----

# Get a sample of whale lengths
sample_length <- function(sp_code, size) {
  # Check species code is valid
  if (!sp_code %in% c("bw", "bp", "mn", "bb")) {
    stop(sprintf("%s is an invalid species code", sp_code))
  }
  # Filter to species
  lengths <- filtration_master %>% 
    filter(SpeciesCode == sp_code) %>% 
    drop_na(whaleLength)
  # Verify available whale lengths
  if (nrow(lengths) == 0) {
    stop(sprintf("No lengths available for %s", sp_code))
  }
  # Draw sample
  sample(lengths$whaleLength, size, replace = TRUE)
}

# Seems to be working
sample_rates <- function(rows, keys) {
  rows_wide <- rows %>% 
    select(ID, Phase, Rate, `Time (hours)`) %>% 
    pivot_wider(names_from = Phase, values_from = c(Rate, `Time (hours)`))
  
  # Skip groups with one animal
  if(nrow(rows_wide) == 1) return(tibble())
  
  sample2 <- function(x, prob, size, replace) {
    tryCatch({
      if (all(prob == 0)) {
        0
      } else {
        sample(x, prob = prob, size = size, replace = replace)
      }
    }, error = function(e) browser())
  }
  
  mass_per_day <- function(rate, capacity, lnmean, lnsd) {
    densities <- rlnorm(rate, lnmean, lnsd)
    sum(capacity * densities)         # This is the line to show Dave; sampling with replacement, is this what we should do? Think about non-independence of samples
  }
  
  # Sample size
  sz <- 10000
  result <- tibble(day_rate = sample2(rows_wide$Rate_Day, prob = rows_wide$`Time (hours)_Day`, size = sz, replace = TRUE),
                   tw_rate = sample2(rows_wide$Rate_Twilight, prob = rows_wide$`Time (hours)_Twilight`, size = sz, replace = TRUE),
                   night_rate = sample2(rows_wide$Rate_Night, prob = rows_wide$`Time (hours)_Night`, size = sz, replace = TRUE),
                   daily_rate = floor(day_rate*14 + tw_rate*3 + night_rate *7),
                   length_distrib = sample_length(keys$SpeciesCode, sz),
                   slope = rows$slope[1],
                   intercept = rows$intercept[1],
                   measured_engulfment_cap_m3 = (length_distrib ^ slope * 10 ^ intercept * 0.9766)/1000,
                   prey_mass_per_day_hyp_low_kg = map2_dbl(daily_rate, measured_engulfment_cap_m3, mass_per_day,  # Other line to show to Dave
                                                   lnmean = rows$prey_hyp_low_lnmean[1],
                                                   lnsd = rows$prey_hyp_low_lnsd[1]),
                   prey_mass_per_day_best_low_kg = map2_dbl(daily_rate, measured_engulfment_cap_m3, mass_per_day, 
                                                           lnmean = rows$prey_best_low_lnmean[1], 
                                                           lnsd = rows$prey_best_low_lnsd[1]),
                   prey_mass_per_day_best_upper_kg = map2_dbl(daily_rate, measured_engulfment_cap_m3, mass_per_day, 
                                                            lnmean = rows$prey_best_upper_lnmean[1], 
                                                            lnsd = rows$prey_best_upper_lnsd[1]),
                   prey_mass_per_lunge = prey_mass_per_day_best_low_kg / daily_rate)
}

d_strapped <- filtration_master %>% 
  filter(
    #Region != "Chile",
    prey_general == "Krill") %>% 
  group_by(Species, SpeciesCode, prey_general, Year, Region) %>% 
  group_modify(sample_rates) %>% 
  ungroup %>% 
  left_join(pop_data, by = "Species")


#Adding in krill energy density in kJ/kg; see scaling paper supplement
d_strapped <-  d_strapped %>% 
  mutate(EnDens_hyp_low = case_when(Region == "Antarctic" ~ 4575*prey_mass_per_day_hyp_low_kg,
                                    Region != "Antarctic" ~ 3370*prey_mass_per_day_hyp_low_kg),
         EnDens_best_low = case_when(Region == "Antarctic" ~ 4575*prey_mass_per_day_best_low_kg,
                                    Region != "Antarctic" ~ 3370*prey_mass_per_day_best_low_kg),
         EnDens_best_upper = case_when(Region == "Antarctic" ~ 4575*prey_mass_per_day_best_upper_kg,
                                    Region != "Antarctic" ~ 3370*prey_mass_per_day_best_upper_kg))




#summary tables of lunges, water filtered, and prey consumed per day----
summ_stats_all <- d_strapped %>% 
  #filter(Species !="Balaenoptera physalus" & Region != "North Atlantic") %>% 
  group_by(Species, Region) %>% 
  summarise(
    `Lunges per day` = median(daily_rate),
    Daily_rate_IQR25 = round(quantile(daily_rate, probs = 0.25, na.rm = TRUE), 2), 
    Daily_rate_IQR75 = round(quantile(daily_rate, probs = 0.75, na.rm = TRUE), 2),
    `Water filtered per day` = median(measured_engulfment_cap_m3*daily_rate),
    Water_filtered_IQR25 = round(quantile(measured_engulfment_cap_m3*daily_rate, probs = 0.25, na.rm = TRUE), 2), 
    Water_filtered_IQR75 = round(quantile(measured_engulfment_cap_m3*daily_rate, probs = 0.75, na.rm = TRUE), 2)) %>% 
  unite("Lunges per day IQR", c(Daily_rate_IQR25, Daily_rate_IQR75), sep = "-") %>% 
  unite("Water filtered per day IQR", c(Water_filtered_IQR25, Water_filtered_IQR75), sep = "-")

summ_prey_stats <- d_strapped %>% 
  filter(!Region %in% c("North Atlantic", "Chile")) %>% 
  group_by(Species, Region) %>% 
  summarise(
    med_daily_consumpt_hyp_low = round(median(prey_mass_per_day_hyp_low_kg), 2),
    med_daily_consumpt_hyp_low_IQR25 = round(quantile(prey_mass_per_day_hyp_low_kg, probs = 0.25, na.rm = TRUE), 2),
    med_daily_consumpt_hyp_low_IQR75 = round(quantile(prey_mass_per_day_hyp_low_kg, probs = 0.75, na.rm = TRUE), 2),
    med_daily_consumpt_best = round(median(prey_mass_per_day_best_low_kg), 2),
    med_daily_consumpt_best_IQR25 = round(quantile(prey_mass_per_day_best_low_kg, probs = 0.25, na.rm = TRUE), 2), 
    med_daily_consumpt_best_IQR75 = round(quantile(prey_mass_per_day_best_low_kg, probs = 0.75, na.rm = TRUE), 2), 
    med_daily_consumpt_top50 = round(median(prey_mass_per_day_best_upper_kg), 2),
    med_daily_consumpt_top50_IQR25 = round(quantile(prey_mass_per_day_best_upper_kg, probs = 0.25, na.rm = TRUE), 2), 
    med_daily_consumpt_top50_IQR75 = round(quantile(prey_mass_per_day_best_upper_kg, probs = 0.75, na.rm = TRUE), 2)) %>% 
  unite("Daily consumption lower estimate IQR", c(med_daily_consumpt_hyp_low_IQR25, med_daily_consumpt_hyp_low_IQR75), sep = "-") %>% 
  unite("Daily consumption IQR", c(med_daily_consumpt_best_IQR25, med_daily_consumpt_best_IQR75), sep = "-") %>% 
  unite("Daily consumption Top 50% IQR", c(med_daily_consumpt_top50_IQR25, med_daily_consumpt_top50_IQR75), sep = "-")


summ_EnDens_krill <- d_strapped %>% 
  filter(!Region %in% c("North Atlantic", "Chile")) %>% 
  group_by(Species, Region) %>% 
  # Daily energy intake in gigajoules (GJ)
  summarise(
    med_daily_En_hyp_low = round(median(EnDens_hyp_low/1e6),2),
    med_daily_En_hyp_low_IQR25 = round(quantile(EnDens_hyp_low/1e6, probs = 0.25, na.rm = TRUE), 2),
    med_daily_En_hyp_low_IQR75 = round(quantile(EnDens_hyp_low/1e6, probs = 0.75, na.rm = TRUE), 2),
    med_daily_En_best = round(median(EnDens_best_low/1e6), 2),
    med_daily_En_best_IQR25 = round(quantile(EnDens_best_low/1e6, probs = 0.25, na.rm = TRUE), 2), 
    med_daily_En_best_IQR75 = round(quantile(EnDens_best_low/1e6, probs = 0.75, na.rm = TRUE), 2), 
    med_daily_En_top50 = round(median(EnDens_best_upper/1e6), 2),
    med_daily_En_top50_IQR25 = round(quantile(EnDens_best_upper/1e6, probs = 0.25, na.rm = TRUE), 2), 
    med_daily_En_top50_IQR75 = round(quantile(EnDens_best_upper/1e6, probs = 0.75, na.rm = TRUE), 2)) %>% 
  unite("Daily energy intake (GJ) lower estimate IQR", c(med_daily_En_hyp_low_IQR25, med_daily_En_hyp_low_IQR75), sep = "-") %>% 
  unite("Daily energy intake (GJ) IQR", c(med_daily_En_best_IQR25, med_daily_En_best_IQR75), sep = "-") %>% 
  unite("Daily energy intake (GJ) Top 50% IQR", c(med_daily_En_top50_IQR25, med_daily_En_top50_IQR75), sep = "-")



# preliminary plots ----

pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")


Measured_length <- ggplot(d_strapped, 
                     aes(x = fct_reorder(abbr_binom(Species), length_distrib), y = length_distrib, 
                         fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  labs(x = "Species",
       y = "Measured length (m)") + 
  theme_classic(base_size = 14) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Measured_length


# Figure 2 Daily rorqual water filtration & krill consumption per individual ----

#ANTARCTIC
Daily_rate_Antarctic <- d_strapped %>% 
  filter(daily_rate >5,
         Region == "Antarctic",
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%  
  ggplot(aes(x = fct_reorder(abbr_binom(Species), daily_rate), y = daily_rate, 
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  #scale_y_continuous(breaks = seq(from = 0, to = 2500, by = 500)) +
  # facet_grid(prey_general~., scales = "free", space = "free",         # freeing scales doesn't work with flat_violin plots
  #            labeller = labeller(prey_general = names(c("Fish-feeding", "Krill-feeding")))) +  #Labeller not working
  labs(x = "Species",
       y = bquote('Estimated feeding rate'~(lunges~ind^-1~d^-1))) + 
  #ylim(0, 2000) +
  scale_y_log10(labels = scales::comma, limits = c(50, 2500), breaks = c(10,100,250,500,1000, 2000)) +
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Daily_rate_Antarctic

dev.copy2pdf(file="Daily_rate_Antarctic.pdf", width=16, height=6)


Daily_filtration_Antarctic <-  d_strapped %>% 
  filter(daily_rate >5,
         Region == "Antarctic",
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%  
  ggplot(aes(x = fct_reorder(abbr_binom(Species), measured_engulfment_cap_m3*daily_rate), y = measured_engulfment_cap_m3*daily_rate, 
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10(labels = scales::comma, breaks = c(100,1000,5000,10000,50000,100000)) +
  #ylim(0,60000) +
  labs(x = "Species",
       y = bquote('Estimated water filtered'~(m^3~ind^-1~d^-1))) + 
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Daily_filtration_Antarctic

dev.copy2pdf(file="Daily_filtration_Antarctic.pdf", width=16, height=6)



Daily_biomass_ingested_Antarctic <- d_strapped %>% 
  filter(daily_rate >5,
         Region == "Antarctic",
         prey_general == "Krill") %>% 
  mutate(Species = fct_relevel(factor(abbr_binom(Species)), "B. bonaerensis")) %>% 
  
  #taking the average of Dave's two distributions
  pivot_longer(cols = c(prey_mass_per_day_best_low_kg, prey_mass_per_day_best_upper_kg),
               names_to = "best_prey_est",
               values_to = "prey_mass_per_day_best_kg") %>% 
  
  ggplot() +
  #hyp-low
  # geom_flat_violin(aes(x = Species, y = prey_mass_per_day_hyp_low_kg/1000,
  #                      fill = abbr_binom(Species)), color = NA, position = position_nudge(x = 0.2, y = 0), alpha = .5, adjust = 2) +
  # geom_boxplot(aes(x = Species, y = prey_mass_per_day_hyp_low_kg/1000,
  #                  fill = abbr_binom(Species)), color = "gray20", width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5,
  #              position = position_nudge(x = -0.12, y = 0)) +
  # #best-low *our best estimate*
  # geom_flat_violin(aes(x = Species, y = prey_mass_per_day_best_low_kg/1000,
  #                      fill = Species), position = position_nudge(x = 0.2, y = 0), alpha = 0.5, adjust = 2) +
  # geom_boxplot(aes(x = Species, y = prey_mass_per_day_best_low_kg/1000,
  #                  fill = abbr_binom(Species)), width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5,
#              position = position_nudge(x = 0.12, y = 0)) +
# #best-upper
# geom_flat_violin(aes(x = Species, y = prey_mass_per_day_best_upper_kg/1000,
#                      fill = Species), position = position_nudge(x = 0.2, y = 0), alpha = 0.5, adjust = 2) +
# geom_boxplot(aes(x = abbr_binom(Species), y = prey_mass_per_day_best_upper_kg/1000,
#                  fill = abbr_binom(Species)), color = "red", width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +

#best *our best estimate, average of best low and best upper*
geom_flat_violin(aes(x = Species, y = prey_mass_per_day_best_kg/1000,
                     fill = Species), position = position_nudge(x = 0.2, y = 0), alpha = 0.8, adjust = 2) +
  geom_boxplot(aes(x = Species, y = prey_mass_per_day_best_kg/1000,
                   fill = abbr_binom(Species)), width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5,
               position = position_nudge(x = 0.12, y = 0)) +
  #ylim(0,100) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  scale_y_log10(labels = scales::comma, limits = c(0.1, 15), breaks = c(0,1,5,10,15)) +
  labs(x = "Species",
       y = bquote('Estimated prey consumed'~(tonnes~ind^-1~d^-1))) +
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Daily_biomass_ingested_Antarctic

dev.copy2pdf(file="Daily_biomass_ingested_Antarctic.pdf", width=16, height=6)


Fig_2_Antarctic <- ggarrange(Daily_rate_Antarctic, Daily_filtration_Antarctic, Daily_biomass_ingested_Antarctic, 
                                labels = c("A", "B", "C"), # THIS IS SO COOL!!
                                font.label = list(size = 18),
                                legend = "none",
                                ncol = 1, nrow = 3)
Fig_2_Antarctic

dev.copy2pdf(file="Fig_2_Antarctic.pdf", width=12, height=18)




#NON-ANTARCTIC
Daily_rate_nonAntarctic <- d_strapped %>% 
  filter(daily_rate >5,
         Region != "Antarctic",
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%  
  ggplot(aes(x = fct_reorder(abbr_binom(Species), daily_rate), y = daily_rate, 
                             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  #scale_y_continuous(breaks = seq(from = 0, to = 2500, by = 500)) +
  # facet_grid(prey_general~., scales = "free", space = "free",         # freeing scales doesn't work with flat_violin plots
  #            labeller = labeller(prey_general = names(c("Fish-feeding", "Krill-feeding")))) +  #Labeller not working
  labs(x = "Species",
       y = bquote('Estimated feeding rate'~(lunges~ind^-1~d^-1))) + 
  #ylim(0, 2000) +
  scale_y_log10(labels = scales::comma, breaks = c(10,100,250,500,1000)) +
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Daily_rate_nonAntarctic

dev.copy2pdf(file="Daily_rate_nonAntarctic.pdf", width=16, height=6)


Daily_filtration_nonAntarctic <-  d_strapped %>% 
  filter(daily_rate >5,
         Region != "Antarctic",
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%  
  ggplot(aes(x = fct_reorder(abbr_binom(Species), measured_engulfment_cap_m3*daily_rate), y = measured_engulfment_cap_m3*daily_rate, 
                         fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10(labels = scales::comma, breaks = c(100,1000,5000,10000,50000,100000)) +
  #ylim(0,60000) +
  labs(x = "Species",
       y = bquote('Estimated water filtered'~(m^3~ind^-1~d^-1))) + 
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Daily_filtration_nonAntarctic

dev.copy2pdf(file="Daily_filtration_Antarctic.pdf", width=16, height=6)



Daily_biomass_ingested_nonAntarctic <- d_strapped %>% 
  filter(daily_rate >5,
         Region != "Antarctic",
         prey_general == "Krill") %>% 
  mutate(Species = fct_relevel(factor(abbr_binom(Species)), "M. novaeangliae", "B. physalus")) %>% 
  
  #taking the average of Dave's two distributions
  pivot_longer(cols = c(prey_mass_per_day_best_low_kg, prey_mass_per_day_best_upper_kg),
               names_to = "best_prey_est",
               values_to = "prey_mass_per_day_best_kg") %>% 
  
  ggplot() +
  #hyp-low
  # geom_flat_violin(aes(x = Species, y = prey_mass_per_day_hyp_low_kg/1000,
  #                      fill = abbr_binom(Species)), color = NA, position = position_nudge(x = 0.2, y = 0), alpha = .5, adjust = 2) +
  # geom_boxplot(aes(x = Species, y = prey_mass_per_day_hyp_low_kg/1000,
  #                  fill = abbr_binom(Species)), color = "gray20", width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5,
  #              position = position_nudge(x = -0.12, y = 0)) +
  # #best-low *our best estimate*
  # geom_flat_violin(aes(x = Species, y = prey_mass_per_day_best_low_kg/1000,
  #                      fill = Species), position = position_nudge(x = 0.2, y = 0), alpha = 0.5, adjust = 2) +
  # geom_boxplot(aes(x = Species, y = prey_mass_per_day_best_low_kg/1000,
  #                  fill = abbr_binom(Species)), width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5,
  #              position = position_nudge(x = 0.12, y = 0)) +
  # #best-upper
  # geom_flat_violin(aes(x = Species, y = prey_mass_per_day_best_upper_kg/1000,
  #                      fill = Species), position = position_nudge(x = 0.2, y = 0), alpha = 0.5, adjust = 2) +
  # geom_boxplot(aes(x = abbr_binom(Species), y = prey_mass_per_day_best_upper_kg/1000,
  #                  fill = abbr_binom(Species)), color = "red", width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  
  #best *our best estimate, average of best low and best upper*
  geom_flat_violin(aes(x = Species, y = prey_mass_per_day_best_kg/1000,
                       fill = Species), position = position_nudge(x = 0.2, y = 0), alpha = 0.8, adjust = 2) +
  geom_boxplot(aes(x = Species, y = prey_mass_per_day_best_kg/1000,
                   fill = abbr_binom(Species)), width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5,
               position = position_nudge(x = 0.12, y = 0)) +
  #ylim(0,100) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  scale_y_log10(labels = scales::comma, limits = c(0.1, 50), breaks = c(0,1,5,10,25, 50)) +
  labs(x = "Species",
       y = bquote('Estimated prey consumed'~(tonnes~ind^-1~d^-1))) +
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Daily_biomass_ingested_nonAntarctic

dev.copy2pdf(file="Daily_biomass_ingested_nonAntarctic.pdf", width=16, height=6)


Fig_2_nonAntarctic <- ggarrange(Daily_rate_nonAntarctic, Daily_filtration_nonAntarctic, Daily_biomass_ingested_nonAntarctic, 
          labels = c("D", "E", "F"), # THIS IS SO COOL!!
          font.label = list(size = 18),
          legend = "none",
          ncol = 1, nrow = 3)
Fig_2_nonAntarctic

dev.copy2pdf(file="Fig_2_nonAntarctic.pdf", width=12, height=18)



# Figure 3 Annual rorqual water filtration & krill consumption per individual ----
 
Yearly_filtration <-  d_strapped %>% 
  filter(daily_rate >5,
         Region != "Antarctic",
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(filtration60 = measured_engulfment_cap_m3*daily_rate*60,
         filtration90 = measured_engulfment_cap_m3*daily_rate*90,
         filtration120 = measured_engulfment_cap_m3*daily_rate*120,
         filtration150 = measured_engulfment_cap_m3*daily_rate*150) %>%
  pivot_longer(cols = starts_with("filt"),
               names_to = "filtering_days",
               names_prefix = "wk",
               values_to = "water_filtered_yr") %>% 
  mutate(filtering_days = factor(filtering_days),
         filtering_days = recode_factor(filtering_days, 
                                      filtration60 = "60 days filtering", 
                                      filtration90 = "90 days filtering", 
                                      filtration120 = "120 days filtering", 
                                      filtration150 = "150 days filtering")) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                       y = water_filtered_yr), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                   y = water_filtered_yr),
                   width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  facet_grid(.~filtering_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10(labels = scales::comma) +
  #ylim(0,60000) +
  labs(x = "Species",
       y = bquote('Estimated water filtered'~(m^3~ind^-1~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_filtration

dev.copy2pdf(file="Yearly_filtration_Antarctic.pdf", width=10, height=6)

# Annual individual filtration, summary table
summ_filt_annual_ind_stats <- Yearly_filtration %>% 
  filter(!Region %in% c("North Atlantic", "Chile")) %>% 
  mutate(Species = abbr_binom(Species)) %>%
  group_by(Species, Region) %>% 
  summarise(
    yr_filt_60days_IQR25 = round(quantile(filtration60, probs = 0.25, na.rm = TRUE), 0),
    yr_filt_60days_IQR75 = round(quantile(filtration60, probs = 0.75, na.rm = TRUE), 0),
    yr_filt_90days_IQR25 = round(quantile(filtration90, probs = 0.25, na.rm = TRUE), 0),
    yr_filt_90days_IQR75 = round(quantile(filtration90, probs = 0.75, na.rm = TRUE), 0),
    yr_filt_120days_IQR25 = round(quantile(filtration120, probs = 0.25, na.rm = TRUE), 0),
    yr_filt_120days_IQR75 = round(quantile(filtration120, probs = 0.75, na.rm = TRUE), 0),
    yr_filt_150days_IQR25 = round(quantile(filtration150, probs = 0.25, na.rm = TRUE), 0),
    yr_filt_150days_IQR75 = round(quantile(filtration150, probs = 0.75, na.rm = TRUE), 0)) %>% 
  unite("Filtration capacity (m3 ind yr), 60 days feeding, IQR", 
        c(yr_filt_60days_IQR25, yr_filt_60days_IQR75), sep = "-") %>% 
  unite("Filtration capacity (m3 ind yr), 90 days feeding, IQR", 
        c(yr_filt_90days_IQR25, yr_filt_90days_IQR75), sep = "-") %>% 
  unite("Filtration capacity (m3 ind yr), 120 days feeding, IQR", 
        c(yr_filt_120days_IQR25, yr_filt_120days_IQR75), sep = "-") %>% 
  unite("Filtration capacity (m3 ind yr), 150 days feeding, IQR", 
        c(yr_filt_150days_IQR25, yr_filt_150days_IQR75), sep = "-")


d_strapped <- filtration_master %>% 
  filter(
    Region != "Chile",
    Region == "Antarctic",
    #!Region %in% c("Chile", "Antarctic"),
    prey_general == "Krill") %>% 
  group_by(Species, SpeciesCode, prey_general, Year, Region) %>% 
  group_modify(sample_rates) %>% 
  ungroup 

d_strapped <- d_strapped %>%
  mutate(Species = fct_relevel(factor(abbr_binom(Species)), "M. novaeangliae", "B. physalus"))

Yearly_prey_ingested <-  d_strapped %>% 
  filter(daily_rate >5,
         #Region != "Antarctic",
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  
  pivot_longer(cols = c(prey_mass_per_day_best_low_kg, prey_mass_per_day_best_upper_kg),
               names_to = "best_prey_est",
               values_to = "prey_mass_per_day_best_kg") %>% 
  
  mutate(prey60 = prey_mass_per_day_best_kg*60,
         prey90 = prey_mass_per_day_best_kg*90,
         prey120 = prey_mass_per_day_best_kg*120,
         prey150 = prey_mass_per_day_best_kg*150) %>%
  pivot_longer(cols = c("prey60", "prey90", "prey120", "prey150"),
               names_to = "feeding_days",
               values_to = "prey_consumed_yr") %>% 
  
  mutate(feeding_days = factor(feeding_days),
         feeding_days = recode_factor(feeding_days, 
                                      prey60 = "60 days feeding", 
                                      prey90 = "90 days feeding", 
                                      prey120 = "120 days feeding", 
                                      prey150 = "150 days feeding")) %>% 

  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x =  Species, y = prey_consumed_yr/1000), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = Species, y = prey_consumed_yr/1000),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  facet_grid(.~feeding_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10(labels = scales::comma) +
  #ylim(0,60000) +
  labs(x = "Species",
       y = bquote('Estimated prey consumed'~(tonnes~ind^-1~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_prey_ingested

dev.copy2pdf(file="Yearly_prey_ingested_Antarctic.pdf", width=10, height=6)



Fig_3_nonAntarctic <- ggarrange(Yearly_filtration, Yearly_prey_ingested, 
                   labels = c("C", "D"), # THIS IS SO COOL!!
                   font.label = list(size = 16),
                   legend = "none",
                   ncol = 1, nrow = 2)
Fig_3_nonAntarctic

dev.copy2pdf(file="Fig_3_nonAntarctic.pdf", width=10, height=10)

# Annual individual krill prey, summary table
summ_prey_annual_ind_stats <- Yearly_prey_ingested %>% 
  filter(!Region %in% c("North Atlantic", "Chile")) %>% 
  mutate(Species = abbr_binom(Species)) %>%
  group_by(Species, Region, feeding_days) %>% 
  summarise(
    yr_prey_IQR25 = round(quantile(prey_consumed_yr, probs = 0.25, na.rm = TRUE)/1000, 2),
    yr_prey_IQR75 = round(quantile(prey_consumed_yr, probs = 0.75, na.rm = TRUE)/1000, 2)) %>% 
  unite("Krill consumption (MMT ind yr) IQR", 
        c(yr_prey_IQR25, yr_prey_IQR75), sep = "-") %>%
  pivot_wider(names_from = feeding_days, values_from = `Krill consumption (MMT ind yr) IQR`)


# Figure 4 filtering ----
pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")

d_strapped <- d_strapped %>%
  mutate(Species = fct_relevel(factor(abbr_binom(Species)), "M. novaeangliae", "B. physalus"))

# Current population numbers
Yearly_filtration_curr_pop <-  d_strapped %>% 
  filter(daily_rate >5,
         #Region == "Antarctic",
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill"))
  
  mutate(filtration60 = measured_engulfment_cap_m3*daily_rate*60*`Population estimate (IUCN 2019)`,
         filtration90 = measured_engulfment_cap_m3*daily_rate*90*`Population estimate (IUCN 2019)`,
         filtration120 = measured_engulfment_cap_m3*daily_rate*120*`Population estimate (IUCN 2019)`,
         filtration150 = measured_engulfment_cap_m3*daily_rate*150*`Population estimate (IUCN 2019)`) %>%
  pivot_longer(cols = starts_with("filt"),
               names_to = "filtering_days",
               names_prefix = "wk",
                values_to = "water_filtered_yr") %>% 
  mutate(filtering_days = factor(filtering_days),
         filtering_days = recode_factor(filtering_days, 
                                        filtration60 = "60 days filtering", 
                                        filtration90 = "90 days filtering", 
                                        filtration120 = "120 days filtering", 
                                        filtration150 = "150 days filtering")) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(Species, water_filtered_yr), y = water_filtered_yr/1e9),
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(Species, water_filtered_yr), y = water_filtered_yr/1e9),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
 # geom_hline(yintercept = 1.3324e9, linetype = "dashed") +  # the total volume of water in the ocean
  facet_grid(.~filtering_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated water filtered by current global population'~(km^3~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_filtration_curr_pop

dev.copy2pdf(file="Yearly_filtration_curr_pop.pdf", width=10, height=6)


summ_filt_annual_pop_stats <- Yearly_filtration_curr_pop %>% 
  filter(!Region %in% c("North Atlantic", "Chile")) %>% 
  mutate(Species = abbr_binom(Species)) %>%
  group_by(Species) %>% 
  summarise(
    yr_filt_60days_IQR25 = round(quantile(filtration60, probs = 0.25, na.rm = TRUE)/1e9, 0),
    yr_filt_60days_IQR75 = round(quantile(filtration60, probs = 0.75, na.rm = TRUE)/1e9, 0),
    yr_filt_90days_IQR25 = round(quantile(filtration90, probs = 0.25, na.rm = TRUE)/1e9, 0),
    yr_filt_90days_IQR75 = round(quantile(filtration90, probs = 0.75, na.rm = TRUE)/1e9, 0),
    yr_filt_120days_IQR25 = round(quantile(filtration120, probs = 0.25, na.rm = TRUE)/1e9, 0),
    yr_filt_120days_IQR75 = round(quantile(filtration120, probs = 0.75, na.rm = TRUE)/1e9, 0),
    yr_filt_150days_IQR25 = round(quantile(filtration150, probs = 0.25, na.rm = TRUE)/1e9, 0),
    yr_filt_150days_IQR75 = round(quantile(filtration150, probs = 0.75, na.rm = TRUE)/1e9, 0)) %>% 
  unite("Filtration capacity (km3 ind yr), 60 days feeding, IQR", 
        c(yr_filt_60days_IQR25, yr_filt_60days_IQR75), sep = "-") %>% 
  unite("Filtration capacity (km3 ind yr), 90 days feeding, IQR", 
        c(yr_filt_90days_IQR25, yr_filt_90days_IQR75), sep = "-") %>% 
  unite("Filtration capacity (km3 ind yr), 120 days feeding, IQR", 
        c(yr_filt_120days_IQR25, yr_filt_120days_IQR75), sep = "-") %>% 
  unite("Filtration capacity (km3 ind yr), 150 days feeding, IQR", 
        c(yr_filt_150days_IQR25, yr_filt_150days_IQR75), sep = "-")


#Historical numbers
pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")


Yearly_filtration_hist_pop <-  d_strapped %>% 
  filter(daily_rate >5,
         #Region == "Antarctic",
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill"))
  
  mutate(filtration60 = measured_engulfment_cap_m3*daily_rate*60*`Historical estimate`,
         filtration90 = measured_engulfment_cap_m3*daily_rate*90*`Historical estimate`,
         filtration120 = measured_engulfment_cap_m3*daily_rate*120*`Historical estimate`,
         filtration150 = measured_engulfment_cap_m3*daily_rate*150*`Historical estimate`) %>%
  pivot_longer(cols = starts_with("filt"),
               names_to = "filtering_days",
               names_prefix = "wk",
               values_to = "water_filtered_yr") %>% 
  mutate(filtering_days = factor(filtering_days),
         filtering_days = recode_factor(filtering_days, 
                                        filtration60 = "60 days filtering", 
                                        filtration90 = "90 days filtering", 
                                        filtration120 = "120 days filtering", 
                                        filtration150 = "150 days filtering")) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(Species, water_filtered_yr), y = water_filtered_yr/1e9),
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(Species, water_filtered_yr), y = water_filtered_yr/1e9),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  #geom_hline(yintercept = 1.3324e9, linetype = "dashed") +  # the total volume of water in the ocean
  facet_grid(.~filtering_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated water filtered by pre-exploitation global population'~(km^3~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_filtration_hist_pop


dev.copy2pdf(file="Yearly_filtration_hist_pop.pdf", width=10, height=6)


Fig_4_filtering <- ggarrange(Yearly_filtration_curr_pop,  Yearly_filtration_hist_pop, 
                             labels = c("A", "B"), # THIS IS SO COOL!!
                             font.label = list(size = 18),
                             legend = "none",
                             ncol = 1, nrow = 2)
Fig_4_filtering

dev.copy2pdf(file="Fig_4_filtering.pdf", width=11, height=12)


# Figure 4 prey consumption ----

# CURRENT ANNUAL PREY CONSUMPTION, ANTARCTICA
Ant_prey_projection <- filtration_master %>% 
  filter(SpeciesCode %in% c("bw", "bp")) %>% 
  mutate(
    Region = case_when(SpeciesCode %in% c("bp", "bw") ~ "Antarctic"),
    prey_best_low_lnmean = case_when(SpeciesCode == "bw" ~ -2.025663,
                                     SpeciesCode == "bp" ~ -2.023616),   #using DC's estimated Antarctic values 
    prey_best_low_lnsd = case_when(SpeciesCode == "bw" ~  0.5180328,
                                   SpeciesCode == "bp" ~  0.5169069),
    prey_best_upper_lnmean = case_when(SpeciesCode == "bw" ~ -1.683988,
                                       SpeciesCode == "bp" ~ -1.669444),
    prey_best_upper_lnsd = case_when(SpeciesCode == "bw" ~ 0.2977463,
                                     SpeciesCode == "bp" ~ 0.2966185)
    
  )


#Need to run d_strapped before all this
d_strapped_Ant_projection <- Ant_prey_projection %>% 
  filter(
    SpeciesCode %in% c("bw", "bp"),
    Region == "Antarctic",
    prey_general == "Krill") %>% 
  group_by(Species, SpeciesCode, prey_general, Year, Region) %>% 
  group_modify(sample_rates) %>% 
  ungroup %>% 
  left_join(pop_data, by = "Species") %>% 
  bind_rows(filter(select(d_strapped, -c(EnDens_hyp_low:EnDens_best_upper)), Region == "Antarctic"))



d_strapped_Ant_projection <- d_strapped_Ant_projection %>%
  mutate(Species = fct_relevel(factor(abbr_binom(Species)), "M. novaeangliae", "B. physalus"))


Yearly_krill_ingested_curr_pop_Antarctic <-  d_strapped_Ant_projection %>% 
  filter(daily_rate >5) %>%   #%in% c("Fish", "Krill")) %>%
  #taking the average of Dave's two distributions
  pivot_longer(cols = c(prey_mass_per_day_best_low_kg, prey_mass_per_day_best_upper_kg),
               names_to = "best_prey_est",
               values_to = "prey_mass_per_day_best_kg") %>% 
  
  mutate(prey60 = prey_mass_per_day_best_kg*`Southern hemisphere population estimate (Christensen 2006)`*60,
         prey90 = prey_mass_per_day_best_kg*`Southern hemisphere population estimate (Christensen 2006)`*90,
         prey120 = prey_mass_per_day_best_kg*`Southern hemisphere population estimate (Christensen 2006)`*120,
         prey150 = prey_mass_per_day_best_kg*`Southern hemisphere population estimate (Christensen 2006)`*150) %>%
  pivot_longer(cols = c("prey60", "prey90", "prey120", "prey150"),
               names_to = "feeding_days",
               values_to = "prey_consumed_yr") %>% 
  
  mutate(feeding_days = factor(feeding_days),
         feeding_days = recode_factor(feeding_days, 
                                      prey60 = "60 days feeding", 
                                      prey90 = "90 days feeding", 
                                      prey120 = "120 days feeding", 
                                      prey150 = "150 days feeding"),
         krill_consumed_yr = case_when(Species == "B. physalus" ~ prey_consumed_yr, 
                                       Species == "B. musculus" ~ prey_consumed_yr,
                                       Species == "M. novaeangliae" ~ prey_consumed_yr,
                                       Species == "B. bonaerensis" ~ prey_consumed_yr)) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                       y = krill_consumed_yr/1000), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                   y = krill_consumed_yr/1000),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  facet_grid(.~feeding_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated krill consumed by current populations'~(tonnes~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_krill_ingested_curr_pop_Antarctic

dev.copy2pdf(file="Yearly_krill_ingested_curr_pop_Antarctic.pdf", width=10, height=6)




summ_prey_annual_pop_stats <- Yearly_krill_ingested_hist_pop_Antarctic %>% 
  #filter(!Region %in% c("North Atlantic", "Chile")) %>% 
  filter(Region == "Antarctic") %>% 
  mutate(Species = abbr_binom(Species)) %>%
  group_by(Species, feeding_days) %>% 
  summarise(
    yr_prey_IQR25 = round(quantile(krill_consumed_yr, probs = 0.25, na.rm = TRUE)/1e9, 2),
    yr_prey_IQR75 = round(quantile(krill_consumed_yr, probs = 0.75, na.rm = TRUE)/1e9, 2)) %>% 
  #pivot_wider(names_from = feeding_days, values_from = yr_prey_IQR25:yr_prey_IQR75)
  #unite("Krill consumption (MMT ind yr) IQR", c(yr_prey_IQR25, yr_prey_IQR75), sep = "-") %>%
  pivot_wider(names_from = feeding_days, values_from = `Krill consumption (MMT ind yr) IQR`)

  
# Summary table for paper's discussion
annual_prey_consumed_summ <- summ_prey_annual_pop_stats %>% 
  group_by(Species) %>% 
  summarise(IQR_25_MMT = mean(yr_prey_IQR25),
            IQR_75_MMT = mean(yr_prey_IQR75))


# CURRENT ANNUAL PREY CONSUMPTION, NON-ANTARCTICA
d_strapped <- d_strapped %>%
  mutate(Species = fct_relevel(factor(abbr_binom(Species)), "B. musculus", "M. novaeangliae",  "B. physalus"))


Yearly_krill_ingested_curr_pop_nonAntarctic <-  d_strapped %>% 
  filter(daily_rate >5,
         Region != "Antarctic",
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  #taking the average of Dave's two distributions
  pivot_longer(cols = c(prey_mass_per_day_best_low_kg, prey_mass_per_day_best_upper_kg),
               names_to = "best_prey_est",
               values_to = "prey_mass_per_day_best_kg") %>% 
  
  mutate(prey60 = prey_mass_per_day_best_kg*(`Population estimate (Christensen 2006)`-`Southern hemisphere population estimate (Christensen 2006)`)*60,
         prey90 = prey_mass_per_day_best_kg*(`Population estimate (Christensen 2006)`-`Southern hemisphere population estimate (Christensen 2006)`)*90,
         prey120 = prey_mass_per_day_best_kg*(`Population estimate (Christensen 2006)`-`Southern hemisphere population estimate (Christensen 2006)`)*120,
         prey150 = prey_mass_per_day_best_kg*(`Population estimate (Christensen 2006)`-`Southern hemisphere population estimate (Christensen 2006)`)*150) %>%
  pivot_longer(cols = c("prey60", "prey90", "prey120", "prey150"),
               names_to = "feeding_days",
               values_to = "prey_consumed_yr") %>% 
  
  mutate(feeding_days = factor(feeding_days),
         feeding_days = recode_factor(feeding_days, 
                                      prey60 = "60 days feeding", 
                                      prey90 = "90 days feeding", 
                                      prey120 = "120 days feeding", 
                                      prey150 = "150 days feeding"),
         krill_consumed_yr = case_when(Species == "B. physalus" ~ prey_consumed_yr*0.8,     # correcting for proportion of diet that is fish; and proportion of individuals not in Southern Hemisphere
                                       Species == "B. musculus" ~ prey_consumed_yr,
                                       Species == "M. novaeangliae" ~ prey_consumed_yr*0.55,
                                       Species == "B. bonaerensis" ~ prey_consumed_yr)) %>% 
  
  ggplot(aes(fill = Species)) +
  geom_flat_violin(aes(x = Species, 
                       y = krill_consumed_yr/1000), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = Species, 
                   y = krill_consumed_yr/1000),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  facet_grid(.~feeding_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated krill consumed by current populations'~(tonnes~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_krill_ingested_curr_pop_nonAntarctic

dev.copy2pdf(file="Yearly_krill_ingested_curr_pop_nonAntarctic.pdf", width=10, height=6)


Fig_4_krill_consume_curr_pop <- ggarrange(Yearly_krill_ingested_curr_pop_Antarctic, Yearly_krill_ingested_curr_pop_nonAntarctic,
                           labels = c("A", "B"), # THIS IS SO COOL!!
                           font.label = list(size = 18),
                           legend = "none",
                           ncol = 1, nrow = 2)
Fig_4_krill_consume_curr_pop

dev.copy2pdf(file="Fig_4_krill_consume_curr_pop.pdf", width=11, height=12)


summ_prey_annual_pop_stats <- Yearly_krill_ingested_hist_pop_nonAntarctic %>% 
  filter(!Region %in% c("North Atlantic", "Chile")) %>% 
  mutate(Species = abbr_binom(Species)) %>%
  group_by(Species, feeding_days) %>% 
  summarise(
    yr_prey_IQR25 = round(quantile(krill_consumed_yr, probs = 0.25, na.rm = TRUE)/1e9, 2),
    yr_prey_IQR75 = round(quantile(krill_consumed_yr, probs = 0.75, na.rm = TRUE)/1e9, 2)) %>% 
  unite("Krill consumption (MMT ind yr) IQR", 
        c(yr_prey_IQR25, yr_prey_IQR75), sep = "-") %>%
  pivot_wider(names_from = feeding_days, values_from = `Krill consumption (MMT ind yr) IQR`)
    




# PRE-EXPLOITATION ANNUAL PREY CONSUMPTION, ANTARCTICA
Yearly_krill_ingested_hist_pop_Antarctic <-  d_strapped_Ant_projection %>% 
  filter(daily_rate >5,
         Region == "Antarctic",
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  #taking the average of Dave's two distributions
  pivot_longer(cols = c(prey_mass_per_day_best_low_kg, prey_mass_per_day_best_upper_kg),
               names_to = "best_prey_est",
               values_to = "prey_mass_per_day_best_kg") %>% 
  
  mutate(prey60 = prey_mass_per_day_best_kg*`Southern hemisphere historic estimate (Christensen 2006)`*60,
         prey90 = prey_mass_per_day_best_kg*`Southern hemisphere historic estimate (Christensen 2006)`*90,
         prey120 = prey_mass_per_day_best_kg*`Southern hemisphere historic estimate (Christensen 2006)`*120,
         prey150 = prey_mass_per_day_best_kg*`Southern hemisphere historic estimate (Christensen 2006)`*150) %>%
  pivot_longer(cols = c("prey60", "prey90", "prey120", "prey150"),
               names_to = "feeding_days",
               values_to = "prey_consumed_yr") %>% 
  
  mutate(feeding_days = factor(feeding_days),
         feeding_days = recode_factor(feeding_days, 
                                      prey60 = "60 days feeding", 
                                      prey90 = "90 days feeding", 
                                      prey120 = "120 days feeding", 
                                      prey150 = "150 days feeding"),
         krill_consumed_yr = case_when(Species == "B. physalus" ~ prey_consumed_yr, 
                                       Species == "B. musculus" ~ prey_consumed_yr,
                                       Species == "M. novaeangliae" ~ prey_consumed_yr,
                                       Species == "B. bonaerensis" ~ prey_consumed_yr)) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                       y = krill_consumed_yr/1000), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                   y = krill_consumed_yr/1000),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  #geom_hline(yintercept = 2.9e5, linetype = "dashed", color = "red") +  # total krill fishery catch from 2018
  geom_hline(yintercept = 3.79e8, linetype = "dashed") +  # the total biomass of E. Superba, best estimate from Atkinson et al. 2009
  facet_grid(.~feeding_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated krill consumed by pre-exploitation populations'~(tonnes~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_krill_ingested_hist_pop_Antarctic

dev.copy2pdf(file="Yearly_krill_ingested_hist_pop_Antarctic.pdf", width=11, height=6)



# PRE-EXPLOITATION ANNUAL PREY CONSUMPTION, NON-ANTARCTICA
d_strapped <- d_strapped %>%
  mutate(Species = fct_relevel(factor(abbr_binom(Species)), "M. novaeangliae", "B. musculus", "B. physalus"))


Yearly_krill_ingested_hist_pop_nonAntarctic <-  d_strapped %>% 
  filter(daily_rate >5,
         Region != "Antarctic",
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  #taking the average of Dave's two distributions
  pivot_longer(cols = c(prey_mass_per_day_best_low_kg, prey_mass_per_day_best_upper_kg),
               names_to = "best_prey_est",
               values_to = "prey_mass_per_day_best_kg") %>% 
  
  mutate(prey60 = prey_mass_per_day_best_kg*(`Historical estimate`-`Southern hemisphere historic estimate (Christensen 2006)`)*60,
         prey90 = prey_mass_per_day_best_kg*(`Historical estimate`-`Southern hemisphere historic estimate (Christensen 2006)`)*90,
         prey120 = prey_mass_per_day_best_kg*(`Historical estimate`-`Southern hemisphere historic estimate (Christensen 2006)`)*120,
         prey150 = prey_mass_per_day_best_kg*(`Historical estimate`-`Southern hemisphere historic estimate (Christensen 2006)`)*150) %>%
  pivot_longer(cols = c("prey60", "prey90", "prey120", "prey150"),
               names_to = "feeding_days",
               values_to = "prey_consumed_yr") %>% 
  
  mutate(feeding_days = factor(feeding_days),
         feeding_days = recode_factor(feeding_days, 
                                      prey60 = "60 days feeding", 
                                      prey90 = "90 days feeding", 
                                      prey120 = "120 days feeding", 
                                      prey150 = "150 days feeding"),
         krill_consumed_yr = case_when(Species == "B. physalus" ~ prey_consumed_yr*0.8,     # correcting for proportion of diet that is fish; and proportion of individuals not in Southern Hemisphere
                                       Species == "B. musculus" ~ prey_consumed_yr,
                                       Species == "M. novaeangliae" ~ prey_consumed_yr*0.55,
                                       Species == "B. bonaerensis" ~ prey_consumed_yr)) %>% 
  
  ggplot(aes(fill = Species)) +
  geom_flat_violin(aes(x = Species, 
                       y = krill_consumed_yr/1000), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = Species, 
                   y = krill_consumed_yr/1000),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  facet_grid(.~feeding_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated krill consumed by pre-exploitation populations'~(tonnes~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_krill_ingested_hist_pop_nonAntarctic

dev.copy2pdf(file="Yearly_krill_ingested_hist_pop_nonAntarctic.pdf", width=11, height=6)


Fig_4_krill_consume_hist_pop <- ggarrange(Yearly_krill_ingested_hist_pop_Antarctic, Yearly_krill_ingested_hist_pop_nonAntarctic,
                   labels = c("C", "D"), # THIS IS SO COOL!!
                   font.label = list(size = 18),
                   legend = "none",
                   ncol = 1, nrow = 2)
Fig_4_krill_consume_hist_pop

dev.copy2pdf(file="Fig_4_krill_consume_hist_pop.pdf", width=11, height=12)


















# Old code below here ----


# Figure 4 Southern Hemisphere krill feeding populations ----
pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")


# Current population numbers
Yearly_filtration_curr_SH_pop <-  d_strapped %>% 
  left_join(pop_data, by = "Species") %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(filtration60 = measured_engulfment_cap_m3*daily_rate*60*`Southern hemisphere population estimate (Christensen 2006)`,
         filtration90 = measured_engulfment_cap_m3*daily_rate*90*`Southern hemisphere population estimate (Christensen 2006)`,
         filtration120 = measured_engulfment_cap_m3*daily_rate*120*`Southern hemisphere population estimate (Christensen 2006)`,
         filtration150 = measured_engulfment_cap_m3*daily_rate*150*`Southern hemisphere population estimate (Christensen 2006)`) %>%
  pivot_longer(cols = starts_with("filt"),
               names_to = "filtering_days",
               names_prefix = "wk",
               values_to = "water_filtered_yr") %>% 
  mutate(filtering_days = factor(filtering_days),
         filtering_days = recode_factor(filtering_days, 
                                        filtration60 = "60 days filtering", 
                                        filtration90 = "90 days filtering", 
                                        filtration120 = "120 days filtering", 
                                        filtration150 = "150 days filtering")) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                       y = water_filtered_yr/1e9), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                   y = water_filtered_yr/1e9),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  facet_grid(.~filtering_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated water filtered by current global population'~(km^3~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_filtration_curr_SH_pop

dev.copy2pdf(file="Yearly_filtration_curr_pop.pdf", width=10, height=6)


#Historical numbers
pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")


Yearly_filtration_hist_SH_pop <-  d_strapped %>% 
  left_join(pop_data, by = "Species") %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(filtration60 = measured_engulfment_cap_m3*daily_rate*60*`Historical estimate`,
         filtration90 = measured_engulfment_cap_m3*daily_rate*90*`Historical estimate`,
         filtration120 = measured_engulfment_cap_m3*daily_rate*120*`Historical estimate`,
         filtration150 = measured_engulfment_cap_m3*daily_rate*150*`Historical estimate`) %>%
  pivot_longer(cols = starts_with("filt"),
               names_to = "filtering_days",
               names_prefix = "wk",
               values_to = "water_filtered_yr") %>% 
  mutate(filtering_days = factor(filtering_days),
         filtering_days = recode_factor(filtering_days, 
                                        filtration60 = "60 days filtering", 
                                        filtration90 = "90 days filtering", 
                                        filtration120 = "120 days filtering", 
                                        filtration150 = "150 days filtering")) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                       y = water_filtered_yr/1e9), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                   y = water_filtered_yr/1e9),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_hline(yintercept = 7180000, linetype = "dashed") +  # the total volume of water in the top 10% of the Southern Ocean
  facet_grid(.~filtering_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated water filtered by pre-exploitation global population'~(km^3~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_filtration_hist_SH_pop

dev.copy2pdf(file="Yearly_filtration_curr_SH_pop.pdf", width=10, height=6)




Krill_catch <- read_csv("AggregatedKrillCatch_CCAMLR.csv") %>% 
  group_by(Calendar_Year) %>% 
  summarise(Total_landing_tonnes = sum(Krill_Green_Weight)) %>% 
  ggplot(aes(Calendar_Year, Total_landing_tonnes)) +
  geom_bar(stat = "identity") +
  theme_classic()
Krill_catch


Yearly_krill_ingested_curr_SH_pop <-  d_strapped %>% 
  left_join(pop_data, by = "Species") %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(prey60 = prey_mass_per_day_best_low_kg*`Southern hemisphere population estimate (Christensen 2006)`*60,
         prey90 = prey_mass_per_day_best_low_kg*`Southern hemisphere population estimate (Christensen 2006)`*90,
         prey120 = prey_mass_per_day_best_low_kg*`Southern hemisphere population estimate (Christensen 2006)`*120,
         prey150 = prey_mass_per_day_best_low_kg*`Southern hemisphere population estimate (Christensen 2006)`*150) %>%
  pivot_longer(cols = c("prey60", "prey90", "prey120", "prey150"),
               names_to = "feeding_days",
               values_to = "prey_consumed_yr") %>% 
  
  mutate(feeding_days = factor(feeding_days),
         feeding_days = recode_factor(feeding_days, 
                                      prey60 = "60 days feeding", 
                                      prey90 = "90 days feeding", 
                                      prey120 = "120 days feeding", 
                                      prey150 = "150 days feeding"),
         krill_consumed_yr = case_when(Species == "Balaenoptera physalus" ~ prey_consumed_yr*0.8,
                                       Species == "Balaenoptera musculus" ~ prey_consumed_yr,
                                       Species == "Megaptera novaeangliae" ~ prey_consumed_yr*0.55,
                                       Species == "Balaenoptera bonaerensis" ~ prey_consumed_yr)) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                       y = krill_consumed_yr/1000), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                   y = krill_consumed_yr/1000),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_hline(yintercept = 2.9e5, linetype = "dashed", color = "red") +  # total krill fishery catch from 2018
  geom_hline(yintercept = 3.79e8, linetype = "dashed") +  # the total biomass of E. Superba, best estimate from Atkinson et al. 2009
  facet_grid(.~feeding_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated prey consumed by current population'~(tonnes~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_krill_ingested_curr_SH_pop

dev.copy2pdf(file="Yearly_prey_ingested_curr_SH_pop.pdf", width=10, height=6)





Yearly_krill_ingested_hist_SH_pop <-  d_strapped %>% 
  left_join(pop_data, by = "Species") %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(prey60 = prey_mass_per_day_best_low_kg*`Southern hemisphere historic estimate (Christensen 2006)`*60,
         prey90 = prey_mass_per_day_best_low_kg*`Southern hemisphere historic estimate (Christensen 2006)`*90,
         prey120 = prey_mass_per_day_best_low_kg*`Southern hemisphere historic estimate (Christensen 2006)`*120,
         prey150 = prey_mass_per_day_best_low_kg*`Southern hemisphere historic estimate (Christensen 2006)`*150) %>%
  pivot_longer(cols = c("prey60", "prey90", "prey120", "prey150"),
               names_to = "feeding_days",
               values_to = "prey_consumed_yr") %>% 
  
  mutate(feeding_days = factor(feeding_days),
         feeding_days = recode_factor(feeding_days, 
                                      prey60 = "60 days feeding", 
                                      prey90 = "90 days feeding", 
                                      prey120 = "120 days feeding", 
                                      prey150 = "150 days feeding"),
         krill_consumed_yr = case_when(Species == "Balaenoptera physalus" ~ prey_consumed_yr*0.8,
                                       Species == "Balaenoptera musculus" ~ prey_consumed_yr,
                                       Species == "Megaptera novaeangliae" ~ prey_consumed_yr*0.55,
                                       Species == "Balaenoptera bonaerensis" ~ prey_consumed_yr)) %>%  
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                       y = krill_consumed_yr/1000), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                   y = krill_consumed_yr/1000),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_hline(yintercept = 2.9e5, linetype = "dashed", color = "red") +  # total krill fishery catch from 2018
  geom_hline(yintercept = 3.79e8, linetype = "dashed") +  # the total biomass of E. Superba, best estimate from Atkinson et al. 2009
  #geom_hline(yintercept = 7.5e8, linetype = "dashed") +  # the total biomass of E. Superba, high estimate from Seigel 2016
  facet_grid(.~feeding_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated prey consumed by pre-exploitation population'~(tonnes~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_krill_ingested_hist_SH_pop 

dev.copy2pdf(file="Yearly_prey_ingested_curr_SH_pop.pdf", width=10, height=6)


Yearly_krill_ingested_SH_pop <- ggarrange(Yearly_krill_ingested_curr_SH_pop, Yearly_krill_ingested_hist_SH_pop, 
                                          labels = c("A", "B"), # THIS IS SO COOL!!
                                          font.label = list(size = 18),
                                          legend = "none",
                                          ncol = 1, nrow = 2)
Yearly_krill_ingested_SH_pop

dev.copy2pdf(file="Yearly_krill_ingested_SH_pop.pdf", width=11, height=12)





##################################
# Create prey consumption function
##################################



# Species specific krill prey weight per m^3----
#from DEC's file BaleenWhaleForagingDistBigKrill100Bins, I think this is the NULL distribution
# Gives mean biomass of krill in kg per m^3----
# prey_dist <- tribble(
#   ~SpeciesCode, ~ln_mean,          ~ln_sd,
#   "bb",     log(10^-0.302053984),  log(10^(0.402095747^2))^0.5,    # E. superba
#   "bp",     log(10^-0.207001968),  log(10^(0.397598067^2))^0.5,    # T.spin
#   "bw",     log(10^-0.200903497),  log(10^(0.391739563^2))^0.5,    # T.spin
#   "mn",     log(10^-0.21552581),  log(10^(0.400348263^2))^0.5      # T.spin
# )

# prey_dist_ENP <- tribble(
#   ~SpeciesCode,     ~ln_mean,             ~ln_sd,
#   "Best_lower",     log(10^0.021189299),  log(10^(0.255272505^2))^0.5,    # T.spin, ALL FROM MRY
#   "Best_upper",     log(10^0.204119983),  log(10^(0.113943352^2))^0.5,    # T.spin, ALL FROM MRY
#   "Hypothetical_low",     log(10^-0.74836178),  0.7374944     #log(10^(-0.514278574)^2)^0.5      # had to calculate manually or NaN is produced
# )


# prey_dist_ENP <- tribble(
#   ~SpeciesCode,     ~ln_mean, ~ln_sd,
#   "Best_lower",     log(1.05),  log(1.8),    # T.spin, ALL FROM MRY
#   "Best_upper",     log(1.6),  log(1.3),    # T.spin, ALL FROM MRY 
#   "Hypothetical_low",  log(0.1785),  log(0.306)     #log(10^(-0.514278574)^2)^0.5      # had to calculate manually or NaN is produced
# )
#   
# example of what a blue whale m3 krill density distribution looks like ----
# index = 1:10000
# MRY_hyp_low_prey_dens_m3 <- rlnorm(1e4, log(1.05) + log(0.17),   log(1.8))  # this hypothetical low distribution used extremely large ENP krill (28mm); AND target strength for E. superba, which is bigger than 28mm 
# MRY_best_lower_prey_dens_m3 <- rlnorm(1e4, log(0.8),  log(1.9)) 
# MRY_best_upper_prey_dens_m3 <- rlnorm(1e4, log(1.6),  log(1.3)) 
# ex_prey_dens <- as.data.frame(cbind(index, MRY_hyp_low_prey_dens_m3, MRY_best_lower_prey_dens_m3, MRY_best_upper_prey_dens_m3))
# 
# ex_prey_dens <- ggplot(ex_prey_dens) + 
#   #geom_histogram(binwidth = 0.1, fill = "gray80") +
#   #geom_density(color = "blue") +
#   #geom_freqpoly(aes(MRY_hyp_low_prey_dens_m3), binwidth = 0.1, color = "gray60") +
#   #geom_freqpoly(aes(MRY_hyp_low_prey_dens_m3), binwidth = 0.1, color = "gray20") +
#   geom_histogram(aes(MRY_best_lower_prey_dens_m3), binwidth = 0.1, color = "blue") +
#   #geom_freqpoly(aes(MRY_best_upper_prey_dens_m3), binwidth = 0.1, color = "red") +
#   labs(x = bquote('krill biomass'~(kg~per~m^3))) +
#   theme_classic(base_size = 18)
# ex_prey_dens






