#####################################
# Forage fish consumption by rorquals 
#####################################

# load data and packages and functions ----
library(data.table)
library(readxl)
library(forcats)
library(tidyverse)
library(ggstance)
library(mgcv)
library(lme4)
library(lmerTest)
library(MuMIn)
library(ggpubr)


SE = function(x){sd(x)/sqrt(sum(!is.na(x)))}

# Abbreviate a binomial e.g. Balaenoptera musculus -> B. musculus
abbr_binom <- function(binom) {
  paste(str_sub(binom, 1, 1), 
        str_extract(binom, " .*"), 
        sep = ".")
}

# Raincloud plot code----
### This script creates an R function to generate raincloud plots, then simulates
### data for plots. If using for your own data, you only need lines 1-80.
### It relies largely dddon code previously written by David Robinson
### (https://gist.github.com/dgrtwo/eb7750e74997891d7c20)
### and the package ggplot2 by Hadley Wickham

# Check if required packages are installed  
packages <- c("cowplot", "readr", "ggplot2", "dplyr", "lavaan", "smooth", "Hmisc")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
}

# Load packages
library(ggplot2)
# Defining the geom_flat_violin (Raincloud) function ----
# Note: the below code modifies the
# existing github page by removing a parenthesis in line 50

"%||%" <- function(a, b) {
  if (!is.null(a)) a else b
}

geom_flat_violin <- function(mapping = NULL, data = NULL, stat = "ydensity",
                             position = "dodge", trim = TRUE, scale = "area",
                             show.legend = NA, inherit.aes = TRUE, ...) {
  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomFlatViolin,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      trim = trim,
      scale = scale,
      ...
    )
  )
}

#' @rdname ggplot2-ggproto
#' @format NULL
#' @usage NULL
#' @export
GeomFlatViolin <-
  ggproto("GeomFlatViolin", Geom,
          setup_data = function(data, params) {
            data$width <- data$width %||%
              params$width %||% (resolution(data$x, FALSE) * 0.9)
            
            # ymin, ymax, xmin, and xmax define the bounding rectangle for each group
            data %>%
              group_by(group) %>%
              mutate(
                ymin = min(y),
                ymax = max(y),
                xmin = x,
                xmax = x + width / 2
              )
          },
          
          draw_group = function(data, panel_scales, coord) {
            # Find the points for the line to go all the way around
            data <- transform(data,
                              xminv = x,
                              xmaxv = x + violinwidth * (xmax - x)
            )
            
            # Make sure it's sorted properly to draw the outline
            newdata <- rbind(
              plyr::arrange(transform(data, x = xminv), y),
              plyr::arrange(transform(data, x = xmaxv), -y)
            )
            
            # Close the polygon: set first and last point the same
            # Needed for coord_polar and such
            newdata <- rbind(newdata, newdata[1, ])
            
            ggplot2:::ggname("geom_flat_violin", GeomPolygon$draw_panel(newdata, panel_scales, coord))
          },
          
          draw_key = draw_key_polygon,
          
          default_aes = aes(
            weight = 1, colour = "grey20", fill = "white", size = 0.5,
            alpha = NA, linetype = "solid"
          ),
          
          required_aes = c("x", "y")
  )








# # feeding rates generated by Max----

# for CATS data
load("~/Documents/Research Data/Whale research/ShirelCh2/rates_CATS.RData")

lunge_rates_CATS <- lunge_rates %>% 
  mutate_at(vars(Rate), ~replace(., is.nan(.), 0)) %>% 
  mutate(tag_type = "CATS")


# for DTAG data

load("~/Documents/Research Data/Whale research/ShirelCh2/rates_DTAG only_9.17.19_long.RData")

lunge_rates_DTAG <- dtag_lunges_long %>% 
  mutate_at(vars(Rate), ~replace(., is.nan(.), 0)) %>% 
  rename(`Time (hours)` = Hours) %>% 
  mutate(prey_general = "Krill",
         Study_Area = "SoCal",
         Region = "Eastern North Pacific",
         tag_type = "DTAG")


load("~/Documents/Research Data/Whale research/ShirelCh2/rates_DTAG_problems addressed.RData")

lunge_rates_DTAG_problems_addressed <- dtag_lunges_long %>% 
  mutate_at(vars(Rate), ~replace(., is.nan(.), 0)) %>% 
  rename(`Time (hours)` = Hours) %>% 
  mutate(prey_general = "Krill",
         Study_Area = "SoCal",
         Region = "Eastern North Pacific",
         tag_type = "DTAG")

lunge_rates_all <- lunge_rates_DTAG_problems_addressed %>% 
  bind_rows(lunge_rates_CATS) %>% 
  mutate(SpeciesCode = substr(ID, 1, 2))

## REMOVE BAD DEPLOYMENTS ###
bad_ID <- read_csv("Bad ID.csv")

# adding in Bryde's deployments from 2018
Brydes_lunges <- read_csv("Brydes_2018_lunge_rates.csv") %>% 
  select(ID, study_area, region, prey_general, duration_h, daylight_h, twilight_h, night_h, total_lunges) 


Brydes_lunges_long <- Brydes_lunges %>% 
  pivot_longer(duration_h:night_h, names_to = "Phase", values_to = "Time (hours)") %>% 
  rename(Study_Area = study_area,
         Region = region, 
         Lunges = total_lunges) %>% 
  mutate(prey_general = "Fish",
         tag_type = "CATS",
         Phase = case_when(Phase == "duration_h" ~ "Total",
                           Phase == "daylight_h" ~ "Day",
                           Phase == "twilight_h" ~ "Twilight",
                           Phase == "night_h" ~ "Night"),
         Rate = Lunges/`Time (hours)`) %>% 
  mutate_at(vars(Rate), ~replace(., is.infinite(.), 0))


#put all deployments together (DTAG and CATS)
lunge_rates_all <- lunge_rates_DTAG_problems_addressed %>% 
  bind_rows(lunge_rates_CATS, Brydes_lunges_long) %>% 
  mutate(SpeciesCode = substr(ID, 1, 2)) %>% 
  anti_join(bad_ID, by = "ID")



# READ IN and COMBINE DATA
# Species-specific average length data (from Shirel's paper) to recalculate average engulfment cap----
v_data <- read_csv("MWmeasurements.csv") %>%
  group_by(Species) %>%
  dplyr::summarize(med_TLm = median(TLm)) %>%
  rename(CommonName = Species) %>%
  mutate(SpeciesCode = case_when(CommonName ==  "Blue Whale" ~ "bw",
                                 CommonName == "Fin Whale"~ "bp",
                                 CommonName ==  "Humpback Whale" ~ "mn",
                                 CommonName == "Minke Whale" ~ "bb",
                                 CommonName == "Bryde's Whale" ~ "be",
                                 CommonName == "Sei Whale" ~ "bs"))
# # # v_data$L <- v_data$MW*0.9766  #creates column that converts MW (kg) to liters

# Allometric equations from Shirel's paper----
# creating fucntions from Shirel's paper for MW (in kg) for engulfment cap in liters for each species where we have a known length
engulf_allo <- tribble(
  ~SpeciesCode, ~slope,   ~intercept,
  "bb",     3.10910,  0.69969,
  "be",     3.1453,   0.5787,
  "bs",     3.05591,   0.77219,
  "bp",     3.54883,  0.15604,
  "bw",     3.667316, -0.014078,
  "mn",     3.24603,  0.85934
)




# Prey data from Dave Cade, recieved on 10/19 ----

# Whale population data---- 
#Current data from IUCN 2019 Redlist, whaling data compiled in Rocha et al. 2014
pop_data <- read_excel("Filtration project_Whale population and feeding information.xlsx", sheet = 1)


#Read in tag guide----
tag_guide <- read_excel("TAG GUIDE_9.5.19.xlsx", skip = 2) %>%  # Skips first two rows
  rename(Study_Area = `Study_Area     _`,
         SpeciesCode = `Spec      _`,
         whaleLength = `Drone  _`) 

tag_guide_ENP <- tag_guide %>% 
  filter(Study_Area %in% c("Monterey", "Cordell Bank", "SoCal", "San Diego", "WA Coast", "Alaska"))
#View(tag_guide_ENP)  # this is for CATS tags only, need to add in DTags for full dataset


# Master filtration rate file----
filtration_master_fish <- lunge_rates_all %>%
  left_join(select(tag_guide, ID, SpeciesCode, Study_Area, whaleLength), by = c("ID", "SpeciesCode")) %>%
  mutate(Study_Area = coalesce(Study_Area.x, Study_Area.y)) %>% 
  select(-c(Study_Area.x, Study_Area.y)) %>% 
  filter(SpeciesCode %in% c("bb", "be", "bp", "bw", "mn", "bs")) %>% 
  mutate(
    Year = substr(ID, 3, 4),
    whaleLength = parse_number(whaleLength),
    Study_Area = replace_na(Study_Area, "SoCal"),
    CommonName = case_when(
      SpeciesCode == "bw" ~ "Blue Whale",
      SpeciesCode == "bp" ~ "Fin Whale",
      SpeciesCode == "bs" ~ "Sei Whale",
      SpeciesCode == "mn" ~ "Humpback Whale",
      SpeciesCode %in% c("ba", "bb") ~ "Minke Whale", 
      TRUE ~ "Bryde's Whale"),
    Species = case_when(
      SpeciesCode == "bw" ~ "Balaenoptera musculus",
      SpeciesCode == "bp" ~ "Balaenoptera physalus",
      SpeciesCode == "mn" ~ "Megaptera novaeangliae",
      SpeciesCode %in% c("bb","ba") ~ "Balaenoptera bonaerensis", 
      SpeciesCode == "be" ~ "Balaenoptera edeni",
      SpeciesCode == "bs" ~ "Balaenoptera borealis"),
    Region = case_when(
      Study_Area %in% c("Monterey", "SoCal", "Cordell Bank", "San Diego", "WA Coast", "Alaska", "Everett")  ~ "Eastern North Pacific",
      Study_Area %in% c("Stellwagen", "Norway", "Azores", "Greenland") ~ "North Atlantic",
      Study_Area == "South Africa" ~ "South Africa",
      Study_Area == "Antarctic" ~ "Antarctic",
      Study_Area == "Chile" ~ "Chile",
      Study_Area == "Falklands" ~ "Falklands")) %>%  
  # Join population numbers
  left_join(pop_data, by = "Species") %>% 
  # Join species-median size data
  left_join(select(v_data, -CommonName), by = "SpeciesCode") %>% 
  # Join allometric equations
  left_join(engulf_allo, by = "SpeciesCode") %>% 
  # Calculate engulfment volumes
  mutate(
    BestLengthEst = coalesce(whaleLength, med_TLm),
    Engulfment_L = BestLengthEst ^ slope * 10 ^ intercept * 0.9766,
    EngulfVolPerHr = Engulfment_L*Rate) %>%     #volume engulfed in liters per hour
  # # adding in krill prey data. Remember: biomass is in kg/m3 here, need to convert back to log to average by region
  # left_join(All_krill_data_ENPcombined, by = c("SpeciesCode", "Region")) %>% 
  # mutate(Study_Area = coalesce(Study_Area.x, Study_Area.y)) %>% 
  # select(-c(Study_Area.x, Study_Area.y)) %>%
  ungroup %>% 
  filter(prey_general == "Fish")




# plots and descriptions of raw data----
Feeding_rates_fish <- filtration_master %>%
  filter(prey_general =="Fish", Phase != "Total", Region != "Chile") %>% 
  group_by(Species, Phase, Region) %>% 
  summarise(
    sample_size = n_distinct(ID),
    med_rate = round(median(Rate), 2),
    IQR25_rate = round(quantile(Rate, probs = 0.25, na.rm = TRUE), 2),
    IQR75_rate = round(quantile(Rate, probs = 0.75, na.rm = TRUE), 2)) %>% 
  pivot_wider(names_from = Phase, values_from = med_rate:IQR75_rate) %>% 
  unite("Day rate IQR", c(IQR25_rate_Day, IQR75_rate_Day), sep = "-") %>% 
  unite("Twilight rate IQR", c(IQR25_rate_Twilight, IQR75_rate_Twilight), sep = "-") %>% 
  unite("Night rate IQR", c(IQR25_rate_Night, IQR75_rate_Night), sep = "-") 



d_strapped <- d_strapped %>%
  mutate(Species = fct_relevel(factor(abbr_binom(Species)), "B. musculus", "M. novaeangliae",  "B. physalus"))


Feeding_rate_h <- filtration_master %>% 
  filter(prey_general %in% c("Fish", "Krill"), 
         Phase == "Total",
         `Time (hours)` > 1) %>%       # %in% c("Day", "Twilight", "Night")) %>%      
  group_by(ID, Species, Engulfment_L, Phase, Rate, prey_general, Year) %>% 
  summarise(whaleLength = first(whaleLength)) %>%
  ungroup %>%
  mutate(prey_general = factor(prey_general),
         prey_general = recode_factor(prey_general, 
                                      Fish = "Fish-feeding", 
                                      Krill = "Krill-feeding"),
         Engulfment_m3 = Engulfment_L/1000) %>% 
  ungroup %>%
  ggplot(aes(x = fct_reorder(abbr_binom(Species), Rate), y = Rate,
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_point(position = position_jitter(width = .05), alpha = 0.6) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  facet_grid(prey_general~., scales = "free", space = "free") +  
  labs(x = "Species",
       y = bquote('Feeding rate'~(lunges~h^-1))) + 
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Feeding_rate_h



################################
## CREATE SAMPLING FUNCTION----
################################

#determining daily feeding rates ----

# Get a sample of whale lengths
sample_length <- function(sp_code, size) {
  # Check species code is valid
  if (!sp_code %in% c("mn", "be", "bp")) {
    stop(sprintf("%s is an invalid species code", sp_code))
  }
  # Filter to species
  lengths <- filtration_master %>% 
    filter(SpeciesCode == sp_code) %>% 
    drop_na(whaleLength)
  # Verify available whale lengths
  if (nrow(lengths) == 0) {
    stop(sprintf("No lengths available for %s", sp_code))
  }
  # Draw sample
  sample(lengths$whaleLength, size, replace = TRUE)
}

# Seems to be working
sample_rates <- function(rows, keys) {
  rows_wide <- rows %>% 
    select(ID, Phase, Rate, `Time (hours)`) %>% 
    pivot_wider(names_from = Phase, values_from = c(Rate, `Time (hours)`))
  
  # Skip groups with one animal
  if(nrow(rows_wide) == 1) return(tibble())
  
  sample2 <- function(x, prob, size, replace) {
    tryCatch({
      if (all(prob == 0)) {
        0
      } else {
        sample(x, prob = prob, size = size, replace = replace)
      }
    }, error = function(e) browser())
  }
  
  mass_per_day <- function(rate, capacity, lnmean, lnsd) {
    densities <- rlnorm(rate, lnmean, lnsd)
    sum(capacity * densities)
  }
  
  mass_per_day <- function(rate, capacity) {
    densities <- rnorm(rate, 7.8*0.4, 7.8*0.1)
    sum(capacity * densities)
  }
  
#I am HERE; EDIT PREY LINES
  # Sample size
  sz <- 10000
  result <- tibble(day_rate = sample2(rows_wide$Rate_Day, prob = rows_wide$`Time (hours)_Day`, size = sz, replace = TRUE),
                   tw_rate = sample2(rows_wide$Rate_Twilight, prob = rows_wide$`Time (hours)_Twilight`, size = sz, replace = TRUE),
                   night_rate = sample2(rows_wide$Rate_Night, prob = rows_wide$`Time (hours)_Night`, size = sz, replace = TRUE),
                   daily_rate = floor(day_rate*14 + tw_rate*3 + night_rate *7),
                   length_distrib = sample_length(keys$SpeciesCode, sz),
                   slope = rows$slope[1],
                   intercept = rows$intercept[1],
                   measured_engulfment_cap_m3 = (length_distrib ^ slope * 10 ^ intercept * 0.9766)/1000)
                   # prey_mass_per_day_hyp_low_kg = map2_dbl(daily_rate, measured_engulfment_cap_m3, mass_per_day,
                   #                                         lnmean = rows$prey_hyp_low_lnmean[1],
                   #                                         lnsd = rows$prey_hyp_low_lnsd[1]),
                   # prey_mass_per_day_best_low_kg = map2_dbl(daily_rate, measured_engulfment_cap_m3, mass_per_day, 
                   #                                          lnmean = rows$prey_best_low_lnmean[1], 
                   #                                          lnsd = rows$prey_best_low_lnsd[1]),
                   # prey_mass_per_day_best_upper_kg = map2_dbl(daily_rate, measured_engulfment_cap_m3, mass_per_day, 
                   #                                            lnmean = rows$prey_best_upper_lnmean[1], 
                   #                                            lnsd = rows$prey_best_upper_lnsd[1]),
                   # prey_mass_per_lunge = prey_mass_per_day_best_low_kg / daily_rate)
}

d_strapped_fish <- filtration_master_fish %>% 
  group_by(Species, SpeciesCode, prey_general, Year, Region) %>% 
  group_modify(sample_rates) %>% 
  ungroup %>% 
  left_join(pop_data, by = "Species")



# Figure 2 fish ----
pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")

Daily_rate_fish <- d_strapped_fish %>% 
  filter(daily_rate >10,
         SpeciesCode != "bp") %>%  
  ggplot(aes(x = fct_reorder(abbr_binom(Species), daily_rate), y = daily_rate, 
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  #scale_y_continuous(breaks = seq(from = 0, to = 2500, by = 500)) +
  # facet_grid(prey_general~., scales = "free", space = "free",         # freeing scales doesn't work with flat_violin plots
  #            labeller = labeller(prey_general = names(c("Fish-feeding", "Krill-feeding")))) +  #Labeller not working
  labs(x = "Species",
       y = bquote('Estimated feeding rate'~(lunges~ind^-1~d^-1))) + 
  #ylim(0, 2000) +
  scale_y_log10(labels = scales::comma, breaks = c(10,100,250,500,1000)) +
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Daily_rate_fish

dev.copy2pdf(file="Daily_rate_fish.pdf", width=16, height=6)


Daily_filtration_fish <- d_strapped_fish %>% 
  filter(daily_rate >10,
         SpeciesCode != "bp") %>%   
  ggplot(aes(x = fct_reorder(abbr_binom(Species), measured_engulfment_cap_m3*daily_rate), y = measured_engulfment_cap_m3*daily_rate, 
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10(labels = scales::comma, breaks = c(100,1000,5000,10000,50000)) +
  #ylim(0,60000) +
  labs(x = "Species",
       y = bquote('Estimated water filtered'~(m^3~ind^-1~d^-1))) + 
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Daily_filtration_fish

dev.copy2pdf(file="Daily_filtration_fish.pdf", width=16, height=6)



Daily_biomass_ingested_nonAntarctic <- d_strapped %>% 
  filter(daily_rate >5,
         Region != "Antarctic",
         prey_general == "Krill") %>% 
  mutate(Species = fct_relevel(factor(abbr_binom(Species)), "M. novaeangliae", "B. physalus")) %>% 
  
  #taking the average of Dave's two distributions
  pivot_longer(cols = c(prey_mass_per_day_best_low_kg, prey_mass_per_day_best_upper_kg),
               names_to = "best_prey_est",
               values_to = "prey_mass_per_day_best_kg") %>% 
  
  ggplot() +
  #hyp-low
  # geom_flat_violin(aes(x = Species, y = prey_mass_per_day_hyp_low_kg/1000,
  #                      fill = abbr_binom(Species)), color = NA, position = position_nudge(x = 0.2, y = 0), alpha = .5, adjust = 2) +
  # geom_boxplot(aes(x = Species, y = prey_mass_per_day_hyp_low_kg/1000,
  #                  fill = abbr_binom(Species)), color = "gray20", width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5,
  #              position = position_nudge(x = -0.12, y = 0)) +
  # #best-low *our best estimate*
  # geom_flat_violin(aes(x = Species, y = prey_mass_per_day_best_low_kg/1000,
  #                      fill = Species), position = position_nudge(x = 0.2, y = 0), alpha = 0.5, adjust = 2) +
  # geom_boxplot(aes(x = Species, y = prey_mass_per_day_best_low_kg/1000,
  #                  fill = abbr_binom(Species)), width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5,
#              position = position_nudge(x = 0.12, y = 0)) +
# #best-upper
# geom_flat_violin(aes(x = Species, y = prey_mass_per_day_best_upper_kg/1000,
#                      fill = Species), position = position_nudge(x = 0.2, y = 0), alpha = 0.5, adjust = 2) +
# geom_boxplot(aes(x = abbr_binom(Species), y = prey_mass_per_day_best_upper_kg/1000,
#                  fill = abbr_binom(Species)), color = "red", width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +

#best *our best estimate, average of best low and best upper*
geom_flat_violin(aes(x = Species, y = prey_mass_per_day_best_kg/1000,
                     fill = Species), position = position_nudge(x = 0.2, y = 0), alpha = 0.8, adjust = 2) +
  geom_boxplot(aes(x = Species, y = prey_mass_per_day_best_kg/1000,
                   fill = abbr_binom(Species)), width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5,
               position = position_nudge(x = 0.12, y = 0)) +
  #ylim(0,100) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  scale_y_log10(labels = scales::comma, limits = c(0.1, 50), breaks = c(0,1,5,10,25, 50)) +
  labs(x = "Species",
       y = bquote('Estimated prey consumed'~(tonnes~ind^-1~d^-1))) +
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Daily_biomass_ingested_nonAntarctic

dev.copy2pdf(file="Daily_biomass_ingested_nonAntarctic.pdf", width=16, height=6)


Fig_2_nonAntarctic <- ggarrange(Daily_rate_nonAntarctic, Daily_filtration_nonAntarctic, Daily_biomass_ingested_nonAntarctic, 
                                labels = c("D", "E", "F"), # THIS IS SO COOL!!
                                font.label = list(size = 18),
                                legend = "none",
                                ncol = 1, nrow = 3)
Fig_2_nonAntarctic

dev.copy2pdf(file="Fig_2_nonAntarctic.pdf", width=12, height=18)

