##################################################################
# Lunge rates and prey consumption calculations and visualizations ----
##################################################################

# load data and packages and fuctions 
library(data.table)
library(readxl)
library(forcats)
library(tidyverse)
library(ggstance)
library(mgcv)
library(lme4)
library(lmerTest)
library(MuMIn)
library(ggpubr)


SE = function(x){sd(x)/sqrt(sum(!is.na(x)))}

# Abbreviate a binomial e.g. Balaenoptera musculus -> B. musculus
abbr_binom <- function(binom) {
  paste(str_sub(binom, 1, 1), 
        str_extract(binom, " .*"), 
        sep = ".")
}

# Raincloud plot code----
### This script creates an R function to generate raincloud plots, then simulates
### data for plots. If using for your own data, you only need lines 1-80.
### It relies largely dddon code previously written by David Robinson
### (https://gist.github.com/dgrtwo/eb7750e74997891d7c20)
### and the package ggplot2 by Hadley Wickham

# Check if required packages are installed  
packages <- c("cowplot", "readr", "ggplot2", "dplyr", "lavaan", "smooth", "Hmisc")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
}

# Load packages
library(ggplot2)
# Defining the geom_flat_violin (Raincloud) function ----
# Note: the below code modifies the
# existing github page by removing a parenthesis in line 50

"%||%" <- function(a, b) {
  if (!is.null(a)) a else b
}

geom_flat_violin <- function(mapping = NULL, data = NULL, stat = "ydensity",
                             position = "dodge", trim = TRUE, scale = "area",
                             show.legend = NA, inherit.aes = TRUE, ...) {
  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomFlatViolin,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      trim = trim,
      scale = scale,
      ...
    )
  )
}

#' @rdname ggplot2-ggproto
#' @format NULL
#' @usage NULL
#' @export
GeomFlatViolin <-
  ggproto("GeomFlatViolin", Geom,
          setup_data = function(data, params) {
            data$width <- data$width %||%
              params$width %||% (resolution(data$x, FALSE) * 0.9)
            
            # ymin, ymax, xmin, and xmax define the bounding rectangle for each group
            data %>%
              group_by(group) %>%
              mutate(
                ymin = min(y),
                ymax = max(y),
                xmin = x,
                xmax = x + width / 2
              )
          },
          
          draw_group = function(data, panel_scales, coord) {
            # Find the points for the line to go all the way around
            data <- transform(data,
                              xminv = x,
                              xmaxv = x + violinwidth * (xmax - x)
            )
            
            # Make sure it's sorted properly to draw the outline
            newdata <- rbind(
              plyr::arrange(transform(data, x = xminv), y),
              plyr::arrange(transform(data, x = xmaxv), -y)
            )
            
            # Close the polygon: set first and last point the same
            # Needed for coord_polar and such
            newdata <- rbind(newdata, newdata[1, ])
            
            ggplot2:::ggname("geom_flat_violin", GeomPolygon$draw_panel(newdata, panel_scales, coord))
          },
          
          draw_key = draw_key_polygon,
          
          default_aes = aes(
            weight = 1, colour = "grey20", fill = "white", size = 0.5,
            alpha = NA, linetype = "solid"
          ),
          
          required_aes = c("x", "y")
  )








# # feeding rates generated by Max----

# for CATS data
load("~/Documents/Research Data/Whale research/ShirelCh2/rates_CATS.RData")

lunge_rates_CATS <- lunge_rates %>% 
  mutate_at(vars(Rate), ~replace(., is.nan(.), 0)) %>% 
  mutate(tag_type = "CATS")


# for DTAG data

load("~/Documents/Research Data/Whale research/ShirelCh2/rates_DTAG only_9.17.19_long.RData")
  
lunge_rates_DTAG <- dtag_lunges_long %>% 
 mutate_at(vars(Rate), ~replace(., is.nan(.), 0)) %>% 
  rename(`Time (hours)` = Hours) %>% 
  mutate(prey_general = "Krill",
         Study_Area = "SoCal",
         Region = "Eastern North Pacific",
         tag_type = "DTAG")


load("~/Documents/Research Data/Whale research/ShirelCh2/rates_DTAG_problems addressed.RData")

lunge_rates_DTAG_problems_addressed <- dtag_lunges_long %>% 
  mutate_at(vars(Rate), ~replace(., is.nan(.), 0)) %>% 
  rename(`Time (hours)` = Hours) %>% 
  mutate(prey_general = "Krill",
         Study_Area = "SoCal",
         Region = "Eastern North Pacific",
         tag_type = "DTAG")

lunge_rates_all <- lunge_rates_DTAG_problems_addressed %>% 
  bind_rows(lunge_rates_CATS) %>% 
  mutate(SpeciesCode = substr(ID, 1, 2))

## REMOVE BAD DEPLOYMENTS ###
bad_ID <- read_csv("Bad ID.csv")

#put all DTAG deployments together 
lunge_rates_all <- lunge_rates_DTAG_problems_addressed %>% 
  bind_rows(lunge_rates_CATS) %>% 
  mutate(SpeciesCode = substr(ID, 1, 2)) %>% 
  anti_join(bad_ID, by = "ID")



# READ IN and COMBINE DATA
# Species-specific average length data (from Shirel's paper) to recalculate average engulfment capacity----
v_data <- read_csv("MWmeasurements.csv") %>%
  group_by(Species) %>%
  dplyr::summarize(med_TLm = median(TLm)) %>%
  rename(CommonName = Species) %>%
  mutate(SpeciesCode = case_when(CommonName ==  "Blue Whale" ~ "bw",
                                 CommonName == "Fin Whale"~ "bp",
                                 CommonName ==  "Humpback Whale" ~ "mn",
                                 CommonName == "Minke Whale" ~ "bb",
                                 CommonName == "Bryde's Whale" ~ "be",
                                 CommonName == "Sei Whale" ~ "bs"))
# # # v_data$L <- v_data$MW*0.9766  #creates column that converts MW (kg) to liters

# Allometric equations from Shirel's paper----
# creating fucntions from Shirel's paper for MW (in kg) for engulfment capacity in liters for each species where we have a known length
engulf_allo <- tribble(
  ~SpeciesCode, ~slope,   ~intercept,
  "bb",     3.10910,  0.69969,
  "be",     3.1453,   0.5787,
  "bs",     3.05591,   0.77219,
  "bp",     3.54883,  0.15604,
  "bw",     3.667316, -0.014078,
  "mn",     3.24603,  0.85934
)


# Species specific krill prey weight per m^3----
#from DEC's file BaleenWhaleForagingDistBigKrill100Bins, I think this is the NULL distribution
# Gives mean biomass of krill in kg per m^3----
# prey_dist <- tribble(
#   ~SpeciesCode, ~ln_mean,          ~ln_sd,
#   "bb",     log(10^-0.302053984),  log(10^(0.402095747^2))^0.5,    # E. superba
#   "bp",     log(10^-0.207001968),  log(10^(0.397598067^2))^0.5,    # T.spin
#   "bw",     log(10^-0.200903497),  log(10^(0.391739563^2))^0.5,    # T.spin
#   "mn",     log(10^-0.21552581),  log(10^(0.400348263^2))^0.5      # T.spin
# )

# prey_dist_ENP <- tribble(
#   ~SpeciesCode,     ~ln_mean,             ~ln_sd,
#   "Best_lower",     log(10^0.021189299),  log(10^(0.255272505^2))^0.5,    # T.spin, ALL FROM MRY
#   "Best_upper",     log(10^0.204119983),  log(10^(0.113943352^2))^0.5,    # T.spin, ALL FROM MRY
#   "Hypothetical_low",     log(10^-0.74836178),  0.7374944     #log(10^(-0.514278574)^2)^0.5      # had to calculate manually or NaN is produced
# )


prey_dist_ENP <- tribble(
  ~SpeciesCode,     ~ln_mean, ~ln_sd,
  "Best_lower",     log(1.05),  log(1.8),    # T.spin, ALL FROM MRY
  "Best_upper",     log(1.6),  log(1.3),    # T.spin, ALL FROM MRY 
  "Hypothetical_low",  log(0.1785),  log(0.306)     #log(10^(-0.514278574)^2)^0.5      # had to calculate manually or NaN is produced
)
  
# example of what a blue whale m3 krill density distribution looks like ----
index = 1:10000
MRY_hyp_low_prey_dens_m3 <- rlnorm(1e4, log(1.05) + log(0.17),   log(1.8))  # this hypothetical low distribution used extremely large ENP krill (28mm); AND target strength for E. superba, which is bigger than 28mm 
MRY_best_lower_prey_dens_m3 <- rlnorm(1e4, log(0.8),  log(1.9)) 
MRY_best_upper_prey_dens_m3 <- rlnorm(1e4, log(1.6),  log(1.3)) 
ex_prey_dens <- as.data.frame(cbind(index, MRY_hyp_low_prey_dens_m3, MRY_best_lower_prey_dens_m3, MRY_best_upper_prey_dens_m3))

ex_prey_dens <- ggplot(ex_prey_dens) + 
  #geom_histogram(binwidth = 0.1, fill = "gray80") +
  #geom_density(color = "blue") +
  #geom_freqpoly(aes(MRY_hyp_low_prey_dens_m3), binwidth = 0.1, color = "gray60") +
  #geom_freqpoly(aes(MRY_hyp_low_prey_dens_m3), binwidth = 0.1, color = "gray20") +
  geom_histogram(aes(MRY_best_lower_prey_dens_m3), binwidth = 0.1, color = "blue") +
  #geom_freqpoly(aes(MRY_best_upper_prey_dens_m3), binwidth = 0.1, color = "red") +
  labs(x = bquote('krill biomass'~(kg~per~m^3))) +
  theme_classic(base_size = 18)
ex_prey_dens


#MRY SOCAL COMBINATION; THINK ABOUT WHAT COMBINATIONS TO USE
 # mean values example
#(log(0.8) + log(0.4))/2
#answer = -0.5697171
# to get back to biomass units exp^answer above; exp is e in R, raise e to logged average to get back to kg units


pooled_log_mean <- function(m1, m2) {
  a = (log(m1) + log(m2))/2
  exp(a)
}

# pooled sd MAYBE ??? ask Dave about this
pooled_sd_mean <- function(sd1, n1, sd2, n2) {
  a = log(sd1^2/n1) + log(sd2^2/n2)
  exp(a)
}





# Whale population data---- 
#Current data from IUCN 2019 Redlist, whaling data compiled in Rocha et al. 2014
pop_data <- read_excel("Filtration project_Whale population and feeding information.xlsx", sheet = 1)


#Read in tag guide----
tag_guide <- read_excel("TAG GUIDE_9.5.19.xlsx", skip = 2) %>%  # Skips first two rows
  rename(Study_Area = `Study_Area     _`,
         SpeciesCode = `Spec      _`,
         whaleLength = `Drone  _`) 

tag_guide_ENP <- tag_guide %>% 
  filter(Study_Area %in% c("Monterey", "Cordell Bank", "SoCal", "San Diego", "WA Coast", "Alaska"))
#View(tag_guide_ENP)  # this is for CATS tags only, need to add in DTags for full dataset

# Master filtration rate file----
filtration_master <- lunge_rates_all %>%
  left_join(select(tag_guide, ID, SpeciesCode, Study_Area, whaleLength), by = c("ID", "SpeciesCode")) %>%
  mutate(Study_Area = coalesce(Study_Area.x, Study_Area.y)) %>% 
  select(-c(Study_Area.x, Study_Area.y)) %>% 
  filter(SpeciesCode %in% c("bb", "be", "bp", "bw", "mn", "bs")) %>% 
  mutate(
    Year = substr(ID, 3, 4),
    whaleLength = parse_number(whaleLength),
    Study_Area = replace_na(Study_Area, "SoCal"),
    CommonName = case_when(
      SpeciesCode == "bw" ~ "Blue Whale",
      SpeciesCode == "bp" ~ "Fin Whale",
      SpeciesCode == "bs" ~ "Sei Whale",
      SpeciesCode == "mn" ~ "Humpback Whale",
      SpeciesCode %in% c("ba", "bb") ~ "Minke Whale", 
      TRUE ~ "Bryde's Whale"),
    Species = case_when(
      SpeciesCode == "bw" ~ "Balaenoptera musculus",
      SpeciesCode == "bp" ~ "Balaenoptera physalus",
      SpeciesCode == "mn" ~ "Megaptera novaeangliae",
      SpeciesCode %in% c("bb","ba") ~ "Balaenoptera bonaerensis", 
      SpeciesCode == "be" ~ "Balaenoptera edeni",
      SpeciesCode == "bs" ~ "Balaenoptera borealis"),
    Region = case_when(
      Study_Area %in% c("Monterey", "SoCal", "Cordell Bank", "San Diego", "WA Coast", "Alaska", "Everett")  ~ "Eastern North Pacific",
      Study_Area %in% c("Stellwagen", "Norway", "Azores", "Greenland") ~ "North Atlantic",
      Study_Area == "South Africa" ~ "South Africa",
      Study_Area == "Antarctic" ~ "Antarctic",
      Study_Area == "Chile" ~ "Chile",
      Study_Area == "Falklands" ~ "Falklands")) %>%  
  # Join population numbers
  left_join(pop_data, by = "Species") %>% 
  # Join species-median size data
  left_join(select(v_data, -CommonName), by = "SpeciesCode") %>% 
  # Join allometric equations
  left_join(engulf_allo, by = "SpeciesCode") %>% 
  # Calculate engulfment volumes
  mutate(
    BestLengthEst = coalesce(whaleLength, med_TLm),
    Engulfment_L = BestLengthEst ^ slope * 10 ^ intercept * 0.9766,
    EngulfVolPerHr = Engulfment_L*Rate) %>% 
  left_join(prey_dist, by = "SpeciesCode") %>% 
  ungroup %>% 
  mutate(prey_hyp_low_lnmean = -1.72316668,
         prey_hyp_low_lnsd = 0.7374944,
         prey_best_low_lnmean = 0.04879016,
         prey_best_low_lnsd = 0.3873574,
         prey_best_upper_lnmean = 0.47000363,
         prey_best_upper_lnsd = 0.1729007)


filtration_master %>%
  group_by(Species) %>%
  summarise(mean_length = median(whaleLength))




# plots of raw data----
  
pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")
  
filter(Region == "Eastern North Pacific", ID != "bw180904-44") %>% 
  group_by(ID, Species) %>% 
  summarise(whaleLength = first(whaleLength)) %>% 
  ungroup %>% 
  mutate(sp_lbl = factor(abbr_binom(Species)) %>% fct_rev) %>% 
  
  
All_droned_lengths <- filtration_master %>% 
  #filter(SpeciesCode %in% c("bw", "bp", "mn")) %>% 
  filter(ID != "bw180904-44") %>% 
  group_by(ID, Species) %>% 
  summarise(whaleLength = first(whaleLength)) %>% 
  ungroup %>% 
  mutate(sp_lbl = factor(abbr_binom(Species)) %>% fct_rev) %>% 
  ggplot(aes(x = sp_lbl, 
             y = whaleLength,
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, outlier.shape = NA, alpha = 0.5) +
  geom_point(position = position_jitter(width = .05), alpha = 0.6) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  labs(x = "Species",
       y = "Measured length (m)") +
  theme_classic(base_size = 18) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
All_droned_lengths
  
dev.copy2pdf(file="All_droned_lengths.pdf", width=12, height=8)


Engulfment_capacity <- filtration_master %>% 
  #filter(ID != "bw180904-44") %>% 
  drop_na(whaleLength) %>% 
  group_by(ID, Species, Engulfment_L) %>% 
  summarise(whaleLength = first(whaleLength)) %>%
  mutate(Engulfment_m3 = Engulfment_L/1000) %>%
  ungroup %>% 
  ggplot(aes(x = fct_reorder(abbr_binom(Species), Engulfment_m3), y = Engulfment_m3,
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.075, y = 0), alpha = .8) +
  geom_boxplot(width = .1, outlier.shape = NA, alpha = 0.5) +
  geom_point(position = position_jitter(width = .05), alpha = 0.6) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  labs(x = "Species",
       y = bquote('Engulfment capacity'~(m^3))) +
  scale_y_log10(labels = scales::comma) +
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Engulfment_capacity

dev.copy2pdf(file="Engulfment_capacity.pdf", width=14, height=6.5)


#plot of feeding rates per hour for ENP species 

Feeding_rate_h <- filtration_master %>% 
  filter(prey_general %in% c("Fish", "Krill"), 
         Phase == "Total",
         `Time (hours)` > 1) %>%       # %in% c("Day", "Twilight", "Night")) %>%      
  group_by(ID, Species, Engulfment_L, Phase, Rate, prey_general, Year) %>% 
  summarise(whaleLength = first(whaleLength)) %>%
  ungroup %>%
  mutate(prey_general = factor(prey_general),
         prey_general = recode_factor(prey_general, 
                                      Fish = "Fish-feeding", 
                                      Krill = "Krill-feeding"),
         Engulfment_m3 = Engulfment_L/1000) %>% 
  ungroup %>%
  ggplot(aes(x = fct_reorder(abbr_binom(Species), Rate), y = Rate,
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_point(position = position_jitter(width = .05), alpha = 0.6) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  facet_grid(prey_general~., scales = "free", space = "free") +  
  labs(x = "Species",
       y = bquote('Feeding rate'~(lunges~h^-1))) + 
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Feeding_rate_h

dev.copy2pdf(file="Feeding_rate_h.pdf", width=14, height=6.5)

prey_consumed_h <- filtration_master %>% 
  filter(Phase == "Total") %>%       # %in% c("Day", "Twilight", "Night")) %>%      
  group_by(ID, Species, Engulfment_L, Phase, Rate, prey_general, Year) %>% 
  summarise(whaleLength = first(whaleLength)) %>%
  mutate(Engulfment_m3 = Engulfment_L/1000) %>%
  ungroup %>% 
  ggplot(aes(x = fct_reorder(abbr_binom(Species), Rate), y = Rate,
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_point(position = position_jitter(width = .05), alpha = 0.6) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  #facet_grid(.~prey_general, scales = "free", space = "free") +  # freeing scales doesn't work with flat_violin plots
  labs(x = "Species",
       y = bquote('Feeding rate'~(lunges~h^-1))) + 
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
prey_consumed_h


dev.copy2pdf(file="Feeding_rate_h.pdf", width=14, height=6.5)



################################
## CREATE SAMPLING FUNCTION----
################################

#determining daily feeding rates ----

# Get a sample of whale lengths
sample_length <- function(sp_code, size) {
  # Check species code is valid
  if (!sp_code %in% c("bw", "bp", "mn", "bb")) {
    stop(sprintf("%s is an invalid species code", sp_code))
  }
  # Filter to species
  lengths <- filtration_master %>% 
    filter(SpeciesCode == sp_code) %>% 
    drop_na(whaleLength)
  # Verify available whale lengths
  if (nrow(lengths) == 0) {
    stop(sprintf("No lengths available for %s", sp_code))
  }
  # Draw sample
  sample(lengths$whaleLength, size, replace = TRUE)
}

# Seems to be working
sample_rates <- function(rows, keys) {
  rows_wide <- rows %>% 
    select(ID, Phase, Rate, `Time (hours)`) %>% 
    pivot_wider(names_from = Phase, values_from = c(Rate, `Time (hours)`))
  
  # Skip groups with one animal
  if(nrow(rows_wide) == 1) return(tibble())
  
  sample2 <- function(x, prob, size, replace) {
    tryCatch({
      if (all(prob == 0)) {
        0
      } else {
        sample(x, prob = prob, size = size, replace = replace)
      }
    }, error = function(e) browser())
  }
  
  mass_per_day <- function(rate, capacity, lnmean, lnsd) {
    densities <- rlnorm(rate, lnmean, lnsd)
    sum(capacity * densities)
  }
  
  # Sample size
  sz <- 10000
  result <- tibble(day_rate = sample2(rows_wide$Rate_Day, prob = rows_wide$`Time (hours)_Day`, size = sz, replace = TRUE),
                   tw_rate = sample2(rows_wide$Rate_Twilight, prob = rows_wide$`Time (hours)_Twilight`, size = sz, replace = TRUE),
                   night_rate = sample2(rows_wide$Rate_Night, prob = rows_wide$`Time (hours)_Night`, size = sz, replace = TRUE),
                   daily_rate = floor(day_rate*14 + tw_rate*3 + night_rate *7),
                   length_distrib = sample_length(keys$SpeciesCode, sz),
                   slope = rows$slope[1],
                   intercept = rows$intercept[1],
                   measured_engulfment_cap_m3 = (length_distrib ^ slope * 10 ^ intercept * 0.9766)/1000,
                   prey_mass_per_day_hyp_low_kg = map2_dbl(daily_rate, measured_engulfment_cap_m3, mass_per_day, 
                                                   lnmean = rows$prey_hyp_low_lnmean[1], 
                                                   lnsd = rows$prey_hyp_low_lnsd[1]),
                   prey_mass_per_day_best_low_kg = map2_dbl(daily_rate, measured_engulfment_cap_m3, mass_per_day, 
                                                           lnmean = rows$prey_best_low_lnmean[1], 
                                                           lnsd = rows$prey_best_low_lnsd[1]),
                   prey_mass_per_day_best_upper_kg = map2_dbl(daily_rate, measured_engulfment_cap_m3, mass_per_day, 
                                                            lnmean = rows$prey_best_upper_lnmean[1], 
                                                            lnsd = rows$prey_best_upper_lnsd[1]),
                   prey_mass_per_lunge = prey_mass_per_day_best_low_kg / daily_rate)
}

d_strapped <- filtration_master %>% 
  #filter(prey_general == "Krill") %>% 
  group_by(Species, SpeciesCode, prey_general, Year, Region) %>% 
  group_modify(sample_rates) %>% 
  ungroup 





# preliminary plots ----

pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")


Measured_length <- ggplot(d_strapped, 
                     aes(x = fct_reorder(abbr_binom(Species), length_distrib), y = length_distrib, 
                         fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  labs(x = "Species",
       y = "Measured length (m)") + 
  theme_classic(base_size = 14) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Measured_length

# Figure 2----

Daily_rate <- d_strapped %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%  
  ggplot(aes(x = fct_reorder(abbr_binom(Species), daily_rate), y = daily_rate, 
                             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  #scale_y_continuous(breaks = seq(from = 0, to = 2500, by = 500)) +
  # facet_grid(prey_general~., scales = "free", space = "free",         # freeing scales doesn't work with flat_violin plots
  #            labeller = labeller(prey_general = names(c("Fish-feeding", "Krill-feeding")))) +  #Labeller not working
  labs(x = "Species",
       y = bquote('Estimated feeding rate'~(lunges~d^-1))) + 
  #ylim(0, 2000) +
  scale_y_log10(labels = scales::comma, breaks = c(10,100,500,1000)) +
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Daily_rate

dev.copy2pdf(file="Daily_rate.pdf", width=16, height=6)


Daily_filtration <-  d_strapped %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%  
  ggplot(aes(x = fct_reorder(abbr_binom(Species), measured_engulfment_cap_m3*daily_rate), y = measured_engulfment_cap_m3*daily_rate, 
                         fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10(labels = scales::comma, breaks = c(100,1000,5000,10000,50000)) +
  #ylim(0,60000) +
  labs(x = "Species",
       y = bquote('Estimated water filtered'~(m^3~d^-1))) + 
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Daily_filtration

dev.copy2pdf(file="Daily_filtration.pdf", width=16, height=6)


Daily_biomass_ingested <- d_strapped %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>% 
  ggplot() +
  #hyp-low
  # geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), prey_mass_per_day_hyp_low_kg), y = prey_mass_per_day_hyp_low_kg/1000, 
  #                      fill = abbr_binom(Species)), color = NA, position = position_nudge(x = 0.2, y = 0), alpha = .4, adjust = 2) +
  # geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), prey_mass_per_day_hyp_low_kg), y = prey_mass_per_day_hyp_low_kg/1000, 
  #                  fill = abbr_binom(Species)), color = "gray20", width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.1,
  #              position = position_nudge(x = -0.12, y = 0)) +
  #best-low *our best estimate*
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), prey_mass_per_day_best_low_kg), y = prey_mass_per_day_best_low_kg/1000, 
                       fill = abbr_binom(Species)), position = position_nudge(x = 0.2, y = 0), alpha = 1, adjust = 2) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), prey_mass_per_day_best_low_kg), y = prey_mass_per_day_best_low_kg/1000, 
                   fill = abbr_binom(Species)), width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.8,
               position = position_nudge(x = 0.12, y = 0)) +
  #best-upper
  # geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), prey_mass_per_day_best_upper_kg), y = prey_mass_per_day_best_upper_kg/1000, 
  #                      fill = abbr_binom(Species)), color = NA, position = position_nudge(x = 0.2, y = 0), alpha = .4, adjust = 2) +
  # geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), prey_mass_per_day_best_upper_kg), y = prey_mass_per_day_best_upper_kg/1000, 
  #                  fill = abbr_binom(Species)), color = "red", width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.1) +
  #ylim(0,100) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  scale_y_log10(labels = scales::comma, limits = c(0.1,100), breaks = c(0,1,10,50,100)) +
  labs(x = "Species",
       y = bquote('Estimated prey consumed'~(tonnes~d^-1))) +
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Daily_biomass_ingested

dev.copy2pdf(file="Daily_biomass_ingested.pdf", width=16, height=6)


Fig_2 <- ggarrange(Daily_rate, Daily_filtration, Daily_biomass_ingested, 
          labels = c("A", "B", "C"), # THIS IS SO COOL!!
          font.label = list(size = 18),
          legend = "none",
          ncol = 1, nrow = 3)
Fig_2

dev.copy2pdf(file="Fig_2.pdf", width=12, height=18)



# Figure 3 ----
pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")

Yearly_filtration <-  d_strapped %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(filtration60 = measured_engulfment_cap_m3*daily_rate*60,
         filtration90 = measured_engulfment_cap_m3*daily_rate*90,
         filtration120 = measured_engulfment_cap_m3*daily_rate*120,
         filtration150 = measured_engulfment_cap_m3*daily_rate*150) %>%
  pivot_longer(cols = starts_with("filt"),
               names_to = "filtering_days",
               names_prefix = "wk",
               values_to = "water_filtered_yr") %>% 
  mutate(filtering_days = factor(filtering_days),
         filtering_days = recode_factor(filtering_days, 
                                      filtration60 = "60 days filtering", 
                                      filtration90 = "90 days filtering", 
                                      filtration120 = "120 days filtering", 
                                      filtration150 = "150 days filtering")) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                       y = water_filtered_yr), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                   y = water_filtered_yr),
                   width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  facet_grid(.~filtering_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10(labels = scales::comma) +
  #ylim(0,60000) +
  labs(x = "Species",
       y = bquote('Estimated water filtered per individual'~(m^3~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_filtration

dev.copy2pdf(file="Yearly_filtration.pdf", width=10, height=6)


Yearly_prey_ingested <-  d_strapped %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(prey60 = prey_mass_per_day_best_low_kg*60,
         prey90 = prey_mass_per_day_best_low_kg*90,
         prey120 = prey_mass_per_day_best_low_kg*120,
         prey150 = prey_mass_per_day_best_low_kg*150) %>%
  pivot_longer(cols = c("prey60", "prey90", "prey120", "prey150"),
               names_to = "feeding_days",
               values_to = "prey_consumed_yr") %>% 
  
  mutate(feeding_days = factor(feeding_days),
         feeding_days = recode_factor(feeding_days, 
                                      prey60 = "60 days feeding", 
                                      prey90 = "90 days feeding", 
                                      prey120 = "120 days feeding", 
                                      prey150 = "150 days feeding")) %>% 

  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), prey_consumed_yr), 
                       y = prey_consumed_yr/1000), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), prey_consumed_yr), 
                   y = prey_consumed_yr/1000),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  facet_grid(.~feeding_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10(labels = scales::comma) +
  #ylim(0,60000) +
  labs(x = "Species",
       y = bquote('Estimated prey consumed per individual'~(tonnes~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_prey_ingested

dev.copy2pdf(file="Yearly_prey_ingested.pdf", width=10, height=6)



Fig_3 <- ggarrange(Yearly_filtration, Yearly_prey_ingested, 
                   labels = c("A", "B"), # THIS IS SO COOL!!
                   font.label = list(size = 16),
                   legend = "none",
                   ncol = 1, nrow = 2)
Fig_3

dev.copy2pdf(file="Fig_3.pdf", width=10, height=10)


# Figure 4 ----
pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")

# Current population numbers
Yearly_filtration_curr_pop <-  d_strapped %>% 
  left_join(pop_data, by = "Species") %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(filtration60 = measured_engulfment_cap_m3*daily_rate*60*`Population estimate (IUCN 2019)`,
         filtration90 = measured_engulfment_cap_m3*daily_rate*90*`Population estimate (IUCN 2019)`,
         filtration120 = measured_engulfment_cap_m3*daily_rate*120*`Population estimate (IUCN 2019)`,
         filtration150 = measured_engulfment_cap_m3*daily_rate*150*`Population estimate (IUCN 2019)`) %>%
  pivot_longer(cols = starts_with("filt"),
               names_to = "filtering_days",
               names_prefix = "wk",
                values_to = "water_filtered_yr") %>% 
  mutate(filtering_days = factor(filtering_days),
         filtering_days = recode_factor(filtering_days, 
                                        filtration60 = "60 days filtering", 
                                        filtration90 = "90 days filtering", 
                                        filtration120 = "120 days filtering", 
                                        filtration150 = "150 days filtering")) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                       y = water_filtered_yr/1000), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                   y = water_filtered_yr/1000),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_hline(yintercept = 1.3324e9, linetype = "dashed") +  # the total volume of water in the ocean
  facet_grid(.~filtering_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated water filtered by current global population'~(km^3~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_filtration_curr_pop

dev.copy2pdf(file="Yearly_filtration_curr_pop.pdf", width=10, height=6)


#Historical numbers
pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")

Yearly_filtration_hist_pop <-  d_strapped %>% 
  left_join(pop_data, by = "Species") %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(filtration60 = measured_engulfment_cap_m3*daily_rate*60*`Historical estimate`,
         filtration90 = measured_engulfment_cap_m3*daily_rate*90*`Historical estimate`,
         filtration120 = measured_engulfment_cap_m3*daily_rate*120*`Historical estimate`,
         filtration150 = measured_engulfment_cap_m3*daily_rate*150*`Historical estimate`) %>%
  pivot_longer(cols = starts_with("filt"),
               names_to = "filtering_days",
               names_prefix = "wk",
               values_to = "water_filtered_yr") %>% 
  mutate(filtering_days = factor(filtering_days),
         filtering_days = recode_factor(filtering_days, 
                                        filtration60 = "60 days filtering", 
                                        filtration90 = "90 days filtering", 
                                        filtration120 = "120 days filtering", 
                                        filtration150 = "150 days filtering")) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                       y = water_filtered_yr/1e9), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                   y = water_filtered_yr/1e9),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_hline(yintercept = 133240000, linetype = "dashed") +  # the total volume of water in the ocean
  facet_grid(.~filtering_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated water filtered by pre-exploitation global population'~(km^3~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_filtration_hist_pop

dev.copy2pdf(file="Yearly_filtration_hist_pop.pdf", width=10, height=6)


Fig_4_filtering <- ggarrange(Yearly_filtration_curr_pop,  Yearly_filtration_hist_pop, 
                             labels = c("A", "B"), # THIS IS SO COOL!!
                             font.label = list(size = 18),
                             legend = "none",
                             ncol = 1, nrow = 2)
Fig_4_filtering

dev.copy2pdf(file="Fig_4_filtering.pdf", width=11, height=12)


Yearly_krill_ingested_curr_pop <-  d_strapped %>% 
  left_join(pop_data, by = "Species") %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(prey60 = prey_mass_per_day_best_low_kg*`Population estimate (IUCN 2019)`*60,
         prey90 = prey_mass_per_day_best_low_kg*`Population estimate (IUCN 2019)`*90,
         prey120 = prey_mass_per_day_best_low_kg*`Population estimate (IUCN 2019)`*120,
         prey150 = prey_mass_per_day_best_low_kg*`Population estimate (IUCN 2019)`*150) %>%
  pivot_longer(cols = c("prey60", "prey90", "prey120", "prey150"),
               names_to = "feeding_days",
               values_to = "prey_consumed_yr") %>% 
  
  mutate(feeding_days = factor(feeding_days),
         feeding_days = recode_factor(feeding_days, 
                                      prey60 = "60 days feeding", 
                                      prey90 = "90 days feeding", 
                                      prey120 = "120 days feeding", 
                                      prey150 = "150 days feeding"),
         krill_consumed_yr = case_when(Species == "Balaenoptera physalus" ~ prey_consumed_yr*0.8,
                                       Species == "Balaenoptera musculus" ~ prey_consumed_yr,
                                       Species == "Megaptera novaeangliae" ~ prey_consumed_yr*0.55,
                                       Species == "Balaenoptera bonaerensis" ~ prey_consumed_yr)) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                       y = krill_consumed_yr/1000), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                   y = krill_consumed_yr/1000),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  facet_grid(.~feeding_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated prey consumed by current populations'~(tonnes~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_krill_ingested_curr_pop

dev.copy2pdf(file="Yearly_krill_ingested_curr_pop.pdf", width=10, height=6)



Yearly_krill_ingested_hist_pop <-  d_strapped %>% 
  left_join(pop_data, by = "Species") %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(prey60 = prey_mass_per_day_best_low_kg*`Historical estimate`*60,
         prey90 = prey_mass_per_day_best_low_kg*`Historical estimate`*90,
         prey120 = prey_mass_per_day_best_low_kg*`Historical estimate`*120,
         prey150 = prey_mass_per_day_best_low_kg*`Historical estimate`*150) %>%
  pivot_longer(cols = c("prey60", "prey90", "prey120", "prey150"),
               names_to = "feeding_days",
               values_to = "prey_consumed_yr") %>% 
  
  mutate(feeding_days = factor(feeding_days),
         feeding_days = recode_factor(feeding_days, 
                                      prey60 = "60 days feeding", 
                                      prey90 = "90 days feeding", 
                                      prey120 = "120 days feeding", 
                                      prey150 = "150 days feeding"),
         krill_consumed_yr = case_when(Species == "Balaenoptera physalus" ~ prey_consumed_yr*0.8,
                                       Species == "Balaenoptera musculus" ~ prey_consumed_yr,
                                       Species == "Megaptera novaeangliae" ~ prey_consumed_yr*0.55,
                                       Species == "Balaenoptera bonaerensis" ~ prey_consumed_yr)) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                       y = krill_consumed_yr/1000), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                   y = krill_consumed_yr/1000),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  facet_grid(.~feeding_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated prey consumed by pre-exploitation populations'~(tonnes~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_krill_ingested_hist_pop 

dev.copy2pdf(file="Yearly_prey_ingested_hist_pop.pdf", width=10, height=6)




Fig_4_feeding <- ggarrange(Yearly_krill_ingested_curr_pop, Yearly_krill_ingested_hist_pop,
                   labels = c("C", "D"), # THIS IS SO COOL!!
                   font.label = list(size = 18),
                   legend = "none",
                   ncol = 1, nrow = 2)
Fig_4_feeding

dev.copy2pdf(file="Fig_4_feeding.pdf", width=11, height=12)







# Figure 4 Southern Hemisphere krill feeding populations ----
pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")


# Current population numbers
Yearly_filtration_curr_SH_pop <-  d_strapped %>% 
  left_join(pop_data, by = "Species") %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(filtration60 = measured_engulfment_cap_m3*daily_rate*60*`Southern hemisphere population estimate (Christensen 2006)`,
         filtration90 = measured_engulfment_cap_m3*daily_rate*90*`Southern hemisphere population estimate (Christensen 2006)`,
         filtration120 = measured_engulfment_cap_m3*daily_rate*120*`Southern hemisphere population estimate (Christensen 2006)`,
         filtration150 = measured_engulfment_cap_m3*daily_rate*150*`Southern hemisphere population estimate (Christensen 2006)`) %>%
  pivot_longer(cols = starts_with("filt"),
               names_to = "filtering_days",
               names_prefix = "wk",
               values_to = "water_filtered_yr") %>% 
  mutate(filtering_days = factor(filtering_days),
         filtering_days = recode_factor(filtering_days, 
                                        filtration60 = "60 days filtering", 
                                        filtration90 = "90 days filtering", 
                                        filtration120 = "120 days filtering", 
                                        filtration150 = "150 days filtering")) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                       y = water_filtered_yr/1e9), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                   y = water_filtered_yr/1e9),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_hline(yintercept = 7180000, linetype = "dashed") +  # the total volume of water in the top 10% of the Southern Ocean
  facet_grid(.~filtering_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated water filtered by current global population'~(km^3~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_filtration_curr_SH_pop

dev.copy2pdf(file="Yearly_filtration_curr_pop.pdf", width=10, height=6)


#Historical numbers
pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")


Yearly_filtration_hist_SH_pop <-  d_strapped %>% 
  left_join(pop_data, by = "Species") %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(filtration60 = measured_engulfment_cap_m3*daily_rate*60*`Historical estimate`,
         filtration90 = measured_engulfment_cap_m3*daily_rate*90*`Historical estimate`,
         filtration120 = measured_engulfment_cap_m3*daily_rate*120*`Historical estimate`,
         filtration150 = measured_engulfment_cap_m3*daily_rate*150*`Historical estimate`) %>%
  pivot_longer(cols = starts_with("filt"),
               names_to = "filtering_days",
               names_prefix = "wk",
               values_to = "water_filtered_yr") %>% 
  mutate(filtering_days = factor(filtering_days),
         filtering_days = recode_factor(filtering_days, 
                                        filtration60 = "60 days filtering", 
                                        filtration90 = "90 days filtering", 
                                        filtration120 = "120 days filtering", 
                                        filtration150 = "150 days filtering")) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                       y = water_filtered_yr/1e9), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), water_filtered_yr), 
                   y = water_filtered_yr/1e9),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_hline(yintercept = 1640, linetype = "dashed") +  # the total volume of water in the top 10% of the Southern Ocean
  facet_grid(.~filtering_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated water filtered by pre-exploitation global population'~(km^3~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_filtration_hist_SH_pop

dev.copy2pdf(file="Yearly_filtration_curr_SH_pop.pdf", width=10, height=6)




Krill_catch <- read_csv("AggregatedKrillCatch_CCAMLR.csv") %>% 
  group_by(Calendar_Year) %>% 
  summarise(Total_landing_tonnes = sum(Krill_Green_Weight)) %>% 
  ggplot(aes(Calendar_Year, Total_landing_tonnes)) +
  geom_bar(stat = "identity") +
  theme_classic()
Krill_catch


Yearly_krill_ingested_curr_SH_pop <-  d_strapped %>% 
  left_join(pop_data, by = "Species") %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(prey60 = prey_mass_per_day_best_low_kg*`Southern hemisphere population estimate (Christensen 2006)`*60,
         prey90 = prey_mass_per_day_best_low_kg*`Southern hemisphere population estimate (Christensen 2006)`*90,
         prey120 = prey_mass_per_day_best_low_kg*`Southern hemisphere population estimate (Christensen 2006)`*120,
         prey150 = prey_mass_per_day_best_low_kg*`Southern hemisphere population estimate (Christensen 2006)`*150) %>%
  pivot_longer(cols = c("prey60", "prey90", "prey120", "prey150"),
               names_to = "feeding_days",
               values_to = "prey_consumed_yr") %>% 
  
  mutate(feeding_days = factor(feeding_days),
         feeding_days = recode_factor(feeding_days, 
                                      prey60 = "60 days feeding", 
                                      prey90 = "90 days feeding", 
                                      prey120 = "120 days feeding", 
                                      prey150 = "150 days feeding"),
         krill_consumed_yr = case_when(Species == "Balaenoptera physalus" ~ prey_consumed_yr*0.8,
                                       Species == "Balaenoptera musculus" ~ prey_consumed_yr,
                                       Species == "Megaptera novaeangliae" ~ prey_consumed_yr*0.55,
                                       Species == "Balaenoptera bonaerensis" ~ prey_consumed_yr)) %>% 
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                       y = krill_consumed_yr/1000), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                   y = krill_consumed_yr/1000),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_hline(yintercept = 2.9e5, linetype = "dashed", color = "red") +  # total krill fishery catch from 2018
  geom_hline(yintercept = 3.79e8, linetype = "dashed") +  # the total biomass of E. Superba, best estimate from Atkinson et al. 2009
  facet_grid(.~feeding_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated prey consumed by current population'~(tonnes~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_krill_ingested_curr_SH_pop

dev.copy2pdf(file="Yearly_prey_ingested_curr_SH_pop.pdf", width=10, height=6)





Yearly_krill_ingested_hist_SH_pop <-  d_strapped %>% 
  left_join(pop_data, by = "Species") %>% 
  filter(daily_rate >5,
         prey_general == "Krill") %>%   #%in% c("Fish", "Krill")) %>%
  mutate(prey60 = prey_mass_per_day_best_low_kg*`Southern hemisphere historic estimate (Christensen 2006)`*60,
         prey90 = prey_mass_per_day_best_low_kg*`Southern hemisphere historic estimate (Christensen 2006)`*90,
         prey120 = prey_mass_per_day_best_low_kg*`Southern hemisphere historic estimate (Christensen 2006)`*120,
         prey150 = prey_mass_per_day_best_low_kg*`Southern hemisphere historic estimate (Christensen 2006)`*150) %>%
  pivot_longer(cols = c("prey60", "prey90", "prey120", "prey150"),
               names_to = "feeding_days",
               values_to = "prey_consumed_yr") %>% 
  
  mutate(feeding_days = factor(feeding_days),
         feeding_days = recode_factor(feeding_days, 
                                      prey60 = "60 days feeding", 
                                      prey90 = "90 days feeding", 
                                      prey120 = "120 days feeding", 
                                      prey150 = "150 days feeding"),
         krill_consumed_yr = case_when(Species == "Balaenoptera physalus" ~ prey_consumed_yr*0.8,
                                       Species == "Balaenoptera musculus" ~ prey_consumed_yr,
                                       Species == "Megaptera novaeangliae" ~ prey_consumed_yr*0.55,
                                       Species == "Balaenoptera bonaerensis" ~ prey_consumed_yr)) %>%  
  
  ggplot(aes(fill = abbr_binom(Species))) +
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                       y = krill_consumed_yr/1000), 
                   position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), krill_consumed_yr), 
                   y = krill_consumed_yr/1000),
               width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_hline(yintercept = 2.9e5, linetype = "dashed", color = "red") +  # total krill fishery catch from 2018
  geom_hline(yintercept = 3.79e8, linetype = "dashed") +  # the total biomass of E. Superba, best estimate from Atkinson et al. 2009
  #geom_hline(yintercept = 7.5e8, linetype = "dashed") +  # the total biomass of E. Superba, high estimate from Seigel 2016
  facet_grid(.~feeding_days, scales = "free", space = "free") +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  scale_y_log10() +
  labs(x = "Species",
       y = bquote('Estimated prey consumed by pre-exploitation population'~(tonnes~yr^-1))) + 
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "italic"))
Yearly_krill_ingested_hist_SH_pop 

dev.copy2pdf(file="Yearly_prey_ingested_curr_SH_pop.pdf", width=10, height=6)


Yearly_krill_ingested_SH_pop <- ggarrange(Yearly_krill_ingested_curr_SH_pop, Yearly_krill_ingested_hist_SH_pop, 
                                          labels = c("A", "B"), # THIS IS SO COOL!!
                                          font.label = list(size = 18),
                                          legend = "none",
                                          ncol = 1, nrow = 2)
Yearly_krill_ingested_SH_pop

dev.copy2pdf(file="Yearly_krill_ingested_SH_pop.pdf", width=11, height=12)





##################################
# Create prey consumption function
##################################







